### ISSUE TITLE
CodeQL started failing yesterday

### ISSUE THREAD

**Issue by mmendelsohn-ns1** [github/codeql-action#1022]
For some reason many of our repo's started failing analysis with a `No queries were specified.` error.  

Here is the complete errror - 

```
Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/codeql with arguments database,init,--db-cluster,/home/runner/work/_temp/codeql_databases,--source-root=/home/runner/work/infra/infra,--language=javascript,--codescanning-config=/home/runner/work/_temp/user-config.yaml.

      Exit code 2 and error was:

      Counting lines of code in /home/runner/work/infra/infra
Resolving extractor javascript.
Successfully loaded extractor JavaScript (javascript) from /opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript.
Created skeleton CodeQL database at /home/runner/work/_temp/codeql_databases/javascript. This in-progress database is ready to be populated by an extractor.
No queries were specified.
```

I looked a day back to when it was working and the 'Load Language Configuration' command was different.  

```
Load language configuration
/opt/hostedtoolcache/CodeQL/0.0.0-20220214/x64/codeql/codeql database init --db-cluster /home/runner/work/_temp/codeql_databases --source-root=/home/runner/work/infra/infra --language=javascript
```

It seems for some reason all the jobs have picked up the addition of `--codescanning-config=/home/runner/work/_temp/user-config.yaml.`
where is this coming from? why did it start? why is it breaking my analysis?  and how do I get rid of it.   

for some reason when I click 're-run' action it runs fine without the --codescanning-config param.

**Comment by mmendelsohn-ns1** [comment]
> 

No they are private. Thank you for the update.

**Comment by edoardopirovano** [comment]
No problem. I'm going to go ahead and close this issue but please do reopen it should you encounter it again.
