### ISSUE TITLE
CodeQL status badge shows failing when the workflow passes.

### ISSUE THREAD

**Issue by WindowsSystemAdmin** [github/codeql-action#1035]
Hello!
I noticed when I run my workflow, the status badge returns failing but the workflow run passing. I tried removing the badge, and creating a new badge but when I try to create a new status badge it says failing. 
![image](https://user-images.githubusercontent.com/44906097/163691123-bd14ffc1-cc0a-4a0c-8ee8-0ddd0e14d8a8.png)
![Screenshot 2022-04-16 4 56 19 PM](https://user-images.githubusercontent.com/44906097/163691131-943cea63-976d-47f1-a610-6b62f0e053dd.png)
![Screenshot 2022-04-16 4 55 48 PM](https://user-images.githubusercontent.com/44906097/163691132-fd030a62-97f6-4a7e-933d-36ed29b3ea00.png)

**Comment by aeisenberg** [comment]
Is this the text of your badge?

```[CodeQL]
(https://github.com/WindowsSystemAdmin/rese
arch/actions/workflows/codeql.yml/badge.svg
?branch=main&event=push)]
(https://github.com/WindowsSystemAdmin/rese
arch/actions/workflows/codeql.yml) ```

I'll get a chance to look at this on Monday.

**Comment by SystemsUser** [comment]
Yes

**Comment by kristylee88** [comment]
Yes

**Comment by WindowsSystemAdmin** [comment]
Yes!

**Comment by aeisenberg** [comment]
Status badges showing incorrectly is part of an ongoing incident. We need to rebuild the index and it is taking some time. We expect all statuses to be back to normal by tomorrow.

**Comment by SystemsUser** [comment]
Awesome! one question, can i change yml to yaml? will my status badge still run?

**Comment by aeisenberg** [comment]
I believe so, but I haven't actually tried this yet. The name is just the file name of the workflow. If you use the `.yaml` file extension and it is working for running your action, then I see no reason why it wouldn't work for the badges.

**Comment by aeisenberg** [comment]
This should be fixed now. At least all known affected repositories should be back to normal. Please let me know if you continue to see invalid status badges.
