### ISSUE TITLE
CodeQL Not catching known CWE's, not failing build for caught CWE

### ISSUE THREAD

**Issue by myoung34** [github/codeql-action#107]
Got them to run as expected per PR #104 

However [this pr](https://github.com/myoung34/tilty/pull/14) should definitely cause a failure for:

* [CWE-377 py/insecure-temporary-file](https://lgtm.com/rules/1507928201922/) -   via `"/opt/hostedtoolcache/CodeQL/0.0.0-20200630/x64/ql/python/ql/src/Security/CWE-377/InsecureTemporaryFile.ql" : { },`
* [CWE-78 py/command-line-injection](https://lgtm.com/rules/1505994646253/) - via `"/opt/hostedtoolcache/CodeQL/0.0.0-20200630/x64/ql/python/ql/src/Security/CWE-078/CommandInjection.ql" : { },`

It did catch CWE-377, but it did not fail the build: ![](https://cdn.zappy.app/d84731bd6ecf0363fab5cc5fbad0144e.png)

It also didnt show much info. I did not realize it caught this until I accidentally clicked on the changes: 

![](https://cdn.zappy.app/c089373d381656e75d98ab50a1c765c9.png)

It does show as a check, but only if you happen to expand it.
The default view: 

![](https://cdn.zappy.app/0583d9de34eb63cc0fa0977d0ce6cc63.png)

If I expand it: ![](https://cdn.zappy.app/6233fef5cb4dea9a5ba43f65800f1a01.png)

This is very very easy to miss and not at all a good UX. I would think that the action itself would fail the build, or that the check would be easier to spot a failure. At a glance the PR looks mergeable.

That said, it still never caught CWE-78

**Comment by myoung34** [comment]
Update: Much later (no changes on my side) it now shows a failed check to the PR: ![](https://cdn.zappy.app/c1ec8c6c44345def355db8a0f699d5c7.png) which is very odd since it wasnt like this for a few hours _after_ i submitted this.

That aside, I'm still a bit curious why CWE-78 isnt triggered

**Comment by robertbrignull** [comment]
@tausbn, do you know why https://github.com/myoung34/tilty/pull/14 didn't trigger https://github.com/github/codeql/blob/master/python/ql/src/Security/CWE-078/CommandInjection.ql?

My guess is that it isn't detecting the source. My what I can tell that query is explicitly looking for `HttpRequestTaintSource` and this doesn't include the `click` library which is for command lines.

**Comment by tausbn** [comment]
Yeah, I think you've got it exactly right. We don't currently model `click` (or any other command line libraries, to my knowledge), so we don't have the necessary sources for the taint tracking to work here.

**Comment by RasmusWL** [comment]
The problem highlighted could only ever trigger https://github.com/github/codeql/blob/df3eb9f9c54335b7d0991ff05451692593982442/python/ql/src/Security/CWE-094/CodeInjection.ql, since `exec` is used (which executes python code, not external programs)

I'm not convinced it's a good example though. The "evil" user that can trigger the `exec` clearly has access to invoke the program from the command line, so from my understanding the "evil" user could just execute the code with `python -c "<command>"`. (I might be mistaking though)

**Comment by myoung34** [comment]
> I'm not convinced it's a good example though. The "evil" user that can trigger the exec clearly has access to invoke the program from the command line, so from my understanding the "evil" user could just execute the code with python -c "<command>". (I might be mistaking though)

The example in question is purely to beta test codeql catches.
I'm investigating using this at our company, so I was hoping to see how the workflows worked in terms of UI/UX and noticed that CWE-78 didn't trigger (after my original issues with CWE-377 started working at some point)

Likely i wrote my example too fast and used `exec()` vs what i really meant: `subprocess.call(executable)`

**Comment by myoung34** [comment]
I'll reopen if this pops back up but it seems to be working as expected now
