### ISSUE TITLE
Build step takes a long time

### ISSUE THREAD

**Issue by lucaspeng12138** [github/codeql-action#1144]
I use codeql in workflow. After init step, build step takes more time than has no codeql one.
I found 16min lost on this location.

![image](https://user-images.githubusercontent.com/100204617/179145650-1c6df5b4-6685-41af-9b35-c9710f354f35.png)

Yaml file is like follow:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/100204617/179145845-fb45ff9e-938d-490c-8368-20cc3f57118f.png">

**Comment by lucaspeng12138** [comment]
I tried several times. If I add -X with mvn install can run nomarlly.

**Comment by lucaspeng12138** [comment]
@aeisenberg Could you please help me out?

**Comment by aeisenberg** [comment]
I can't say for sure without he full logs. Some questions though:

1. Why are you using CI: false?
2. Perhaps try removing the cache step.
3. The 15 minute gap implies there is a network issue. Are you on a self-hosted runner? Is this gap repeatable?

**Comment by lucaspeng12138** [comment]
It's hardly repeatable
Once I used -X and I found this exception:
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/100204617/179663776-3e8eea3f-e2d8-48fd-9ee8-97178e2a9d8c.png">

I think this may be some wrong with repository

**Comment by aeisenberg** [comment]
That makes sense. Take a look if repository.jboss.com has any issues right now, or if that particular artifact is corrupt.

**Comment by lucaspeng12138** [comment]
@aeisenberg thanks a lot
