### ISSUE TITLE
Suggest updating the github uploading a Sarif file docs

### ISSUE THREAD

**Issue by jsoref** [github/codeql-action#1173]
https://github.com/github/codeql-action/blob/1fae5bf71b0ecdc7d0a2ef0d0c28409d99693966/CONTRIBUTING.md#releasing-write-access-required
Has a series of steps for making a new release.

One thing it doesn't cover is ensuring that the [github/docs](https://github.com/github/docs) are current.

At present, the [github docs](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions) point to the [upload-sarif action](https://github.com/github/codeql-action/tree/v1/upload-sarif) (`v1/upload-sarif`):
https://github.com/github/docs/blame/5f4ef9a6217181efc12e67463894783496fb0c79/content/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github.md#L57

It seems likely that the docs should point to `releases/v2` in some way, shape, or form (this might be a SHA -- see [Using third-party actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions): Pin actions to a full length commit SHA, or it might be the latest `2.x.y` tag).

Since I don't really yet understand this action, I'm going to leave the negotiation between this repository and the [github/docs](https://github.com/github/docs) repository to the owners of this repository as you should be in a better position to characterize the right content than I could be.

**Comment by aeisenberg** [comment]
Thanks for pointing this out. We'll take a look and update the links.

**Comment by aeisenberg** [comment]
Link is fixed internally and should be released soon.
