### ISSUE TITLE
Poetry 1.2 support

### ISSUE THREAD

**Issue by DeadNews** [github/codeql-action#1241]
ref: https://github.com/github/codeql-action/commit/8c692b37a0046ac517887cfa674f65483a82ae92

https://github.com/github/codeql-action/blob/9ba4d500aa0261992135290a8c8eff47a4bb2ecb/CHANGELOG.md?plain=1#L11

CodeQL will not work with projects that use the new Poetry 1.2 features, such as [dependency-groups](
https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups):
>As the dev-dependencies is now deprecated, projects should migrate to the new group syntax as soon as possible. Keep in mind that the group syntax is a new feature of Poetry 1.2, and your project will not be buildable with Poetry 1.1 after migrating.

[CodeQL error](https://github.com/DeadNews/deadnews-python-template/runs/8250971693?check_suite_focus=true#step:3:298):
>Warning: An error occurred while trying to automatically install Python dependencies: Error: The process '/usr/bin/python3' failed with exit code 1

**Comment by aeisenberg** [comment]
Thanks for your feature request. We have added this to our backlog and will discuss this at our next planning meeting.
