### ISSUE TITLE
C# .NET Framework 4.8.1

### ISSUE THREAD

**Issue by Taiizor** [github/codeql-action#1255]
.NET Framework version 4.8.1 has problems when analyzing.

![image](https://user-images.githubusercontent.com/41683699/190681235-b2d17ab0-e71b-4b74-ac7c-83e83042547f.png)

![image](https://user-images.githubusercontent.com/41683699/190681173-84c91f3c-93bf-480a-bd35-b52ff3079151.png)

Below are the analysis results.
https://github.com/Taiizor/ReaLTaiizor/actions/runs/3065068356/jobs/4948793777

**Comment by edoardopirovano** [comment]
Greetings, thanks for getting in touch with this. I've filed https://github.com/Taiizor/ReaLTaiizor/pull/77, which should fix the CodeQL workflow for you. I've explained on the pull request what changes I made and why. Do let me know if you have any questions, or if I can be of further help.

**Comment by edoardopirovano** [comment]
PR is merged and the workflow seems to be succeeding now: https://github.com/Taiizor/ReaLTaiizor/actions/runs/3090079939

Closing this issue as I believe it is resolved, but do let me know if you'd like any further help with CodeQL.

**Comment by Taiizor** [comment]
> PR is merged and the workflow seems to be succeeding now: https://github.com/Taiizor/ReaLTaiizor/actions/runs/3090079939
> 
> Closing this issue as I believe it is resolved, but do let me know if you'd like any further help with CodeQL.

I am grateful for your interest and the work you have done. Everything seems to be fine right now. Otherwise, I will contact you (:
