### ISSUE TITLE
use plugin `frontend-maven-plugin` not working

### ISSUE THREAD

**Issue by qianmoQ** [github/codeql-action#1260]
use plugin `frontend-maven-plugin` not working

```
Error: 9-20 07:51:04] [autobuild] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm install) on project datacap-server: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220825/x64/codeql/java/tools/autobuild.sh with arguments .
  
        Exit code 1 and error was:
  
        Picked up JAVA_TOOL_OPTIONS:  -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
  
  CommandInvocationError: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220825/x64/codeql/java/tools/autobuild.sh with arguments .
  
        Exit code 1 and error was:
  
        Picked up JAVA_TOOL_OPTIONS:  -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
  
      at runTool (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:867:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.runAutobuild (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:559:13)
      at async runAutobuild (/home/runner/work/_actions/github/codeql-action/v2/lib/autobuild.js:97:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/autobuild-action.js:71:17)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/autobuild-action.js:88:9)
```

**Comment by edoardopirovano** [comment]
Greetings, thanks for reaching out with this. Do you have a link to a failing run of CodeQL that we could look at if the repository is public? This looks like we're failing to automatically determine how to build your code, perhaps because we're building a target that isn't working. Without seeing the repository, it's hard to know what specifically count be going wrong, but my suggestion would be to replace the `github/codeql-action/autobuild@v2` step of your workflow with a manual step that invokes a build target that can build the code you wish to analyze.

**Comment by qianmoQ** [comment]
> 如果存储库是正在自动运行的链接，是否有指向失败的 CodeQL 正在运行的链接，我们可以查看链接，我们无法确定您与此联系的可能，是因为我们如果不查看创建一个您的创建工作的存储库，但知道具体触发目标的错误用处，我的建议是`github/codeql-action/autobuild@v2`手动希望的操作流程分析的步骤，步骤调用可以创建目标。

https://github.com/EdurtIO/incubator-datacap/actions/runs/3088388999/jobs/4994797515

**Comment by qianmoQ** [comment]
> Greetings, thanks for reaching out with this. Do you have a link to a failing run of CodeQL that we could look at if the repository is public? This looks like we're failing to automatically determine how to build your code, perhaps because we're building a target that isn't working. Without seeing the repository, it's hard to know what specifically count be going wrong, but my suggestion would be to replace the `github/codeql-action/autobuild@v2` step of your workflow with a manual step that invokes a build target that can build the code you wish to analyze.

Let me try that
