### ISSUE TITLE
Issue while adding custom queries

### ISSUE THREAD

**Issue by chiragagrawal026** [github/codeql-action#1283]
Hey this is the error I'm facing while creating custom queries in codeql Javascript.

` Error: Error running analysis for javascript: Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/codeql with arguments database,interpret-results,--threads=2,--format=sarif-latest,-v,--output=../results/javascript.sarif,--no-sarif-add-snippets,--print-diagnostics-summary,--print-metrics-summary,--sarif-group-rules-by-pack,--sarif-add-query-help,--sarif-category,/language:javascript,/home/runner/work/_temp/codeql_databases/javascript,/home/runner/work/_temp/codeql_databases/javascript-queries-builtin.qls,/home/runner/work/_temp/codeql_databases/javascript-queries-custom-0.qls,/home/runner/work/_temp/codeql_databases/javascript-queries-custom-1.qls.`

` Exit code 2 and error was:

      Writing logs to /home/runner/work/_temp/codeql_databases/javascript/log/database-interpret-results-20221005.185004.910.log.
Recording pack reference codeql/javascript-queries at /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/qlpacks/codeql/javascript-queries/0.4.0.
Recording pack reference grid-js-queries at /home/runner/work/edp/edp/.github/codeql-queries/grid-js-queries.
Scanning for [codeql-pack.yml, qlpack.yml] from /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/.codeqlmanifest.json
Scanning for [codeql-pack.yml, qlpack.yml] from /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/
Not scanning from /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql which is already done.`

Please help I have a project due tomorrow.
Thanks in advance.

**Comment by adityasharad** [comment]
Could you please share the full error log, or a link to a public workflow run? The actual error is further down from the snippet you shared.

**Comment by adityasharad** [comment]
```
A fatal error occurred: Could not process query metadata for /home/runner/work/edp/edp/.github/codeql-queries/grid-js-queries/outbound-request.ql.
  Error was: Cannot process query metadata for a query without the '@kind' metadata property. To learn more, see https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries/ [NO_KIND_SPECIFIED]
  Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/codeql with arguments database,interpret-results,--threads=2,--format=sarif-latest,-v,--output=../results/javascript.sarif,--no-sarif-add-snippets,--print-diagnostics-summary,--print-metrics-summary,--sarif-group-rules-by-pack,--sarif-add-query-help,--sarif-category,/language:javascript,/home/runner/work/_temp/codeql_databases/javascript,/home/runner/work/_temp/codeql_databases/javascript-queries-builtin.qls,/home/runner/work/_temp/codeql_databases/javascript-queries-custom-0.qls,/home/runner/work/_temp/codeql_databases/javascript-queries-custom-1.qls.
```

This is the error. Your custom query is missing the query metadata section, particularly `@kind path-problem`. Please see https://codeql.github.com/docs/writing-codeql-queries/metadata-for-codeql-queries for more information. Thanks for trying out CodeQL and developing your own queries!

**Comment by chiragagrawal026** [comment]
Hey, thank you so much for this.
It really helped!
