### ISSUE TITLE
Error: No code found during the build -- for a project using C.

### ISSUE THREAD

**Issue by dopey** [github/codeql-action#1292]
I’m not quire sure why the action is unable to find any code or binaries to analyze.

Here's the run: https://github.com/smallstep/pkcs11-proxy/actions/runs/3212053239/jobs/5250635125. I'm using my own command to `cmake` and `make` the binary (as well as the .so files). I've SSH-ed into the build to validate that the binary and .so files are present inside the current tree structure. Not sure what else CodeQL might be expecting. Any guidance would be appreciated. Thanks!

**Comment by jketema** [comment]
Thanks for your question. It seems you're running `cmake` and `make` as root (using `sudo`). This means CodeQL will not be able to pick up on the underlying compiler invocations, as they are executed by a different user.

Looking at your workflow, I expect it should be sufficient to replace:
```yaml
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y bash curl git-core build-essential pkg-config cmake libssl-dev libseccomp-dev
        sudo cmake .
        sudo make
        sudo make install
        mkdir bin
        sudo cp /usr/local/lib/libpkcs11-proxy.so.0.1 ./bin/
        sudo cp /usr/local/lib/libpkcs11-proxy.so.0 ./bin/
        sudo cp /usr/local/lib/libpkcs11-proxy.so ./bin/
        sudo cp /usr/local/bin/pkcs11-daemon ./bin/
        sudo chown -R runner:docker ./bin
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
```
by:
```
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y bash curl git-core build-essential pkg-config cmake libssl-dev libseccomp-dev
        cmake .
        make
```

**Comment by dopey** [comment]
Yep, that was it. Thanks a ton for the help!
