### ISSUE TITLE
Exit code 2 when running 'codeql database run-queries'.

### ISSUE THREAD

**Issue by liushilongbuaa** [github/codeql-action#1302]
[167/167 eval 5.9s] Evaluation done; writing results to codeql/python-queries/Variables/UnusedModuleVariable.bqrs.
  Shutting down query evaluator.
  /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/codeql database run-queries --ram=5919 --threads=2 /home/runner/work/_temp/codeql_databases/python --min-disk-free=1024 -v --additional-packs /home/runner/work/_temp/github/codeql/main /home/runner/work/_temp/codeql_databases/python-queries-custom-0.qls
  Writing logs to /home/runner/work/_temp/codeql_databases/python/log/database-run-queries-20221014.072055.117.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/python/log/execute-queries-20221014.072055.675.log.
  Recording pack reference codeql/python-queries at /home/runner/work/_temp/github/codeql/main/python/ql/src.
  Did not find any ML models.
  Compiling in one thread due to RAM limits.
  Compiling query plan for /home/runner/work/_temp/github/codeql/main/python/ql/src/Expressions/UseofInput.ql.
  Resolving imports for /home/runner/work/_temp/github/codeql/main/python/ql/src/Expressions/UseofInput.ql.
  Checking QL for /home/runner/work/_temp/github/codeql/main/python/ql/src/Expressions/UseofInput.ql.
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:841,3-13)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:847,3-13)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:863,3-13)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:910,3-13)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1002,3-13)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1263,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1487,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1665,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1678,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1684,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1705,5-15)
  ERROR: unknown annotation additional (/home/runner/work/_temp/github/codeql/main/python/ql/lib/semmle/python/dataflow/new/internal/DataFlowImpl.qll:1747,5-15)
  Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/codeql with arguments database,run-queries,--ram=5919,--threads=2,/home/runner/work/_temp/codeql_databases/python,--min-disk-free=1024,-v,--additional-packs,/home/runner/work/_temp/github/codeql/main,/home/runner/work/_temp/codeql_databases/python-queries-custom-0.qls.
  
        Exit code 2 and error was:
  
        Writing logs to /home/runner/work/_temp/codeql_databases/python/log/database-run-queries-20221014.072055.117.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/python/log/execute-queries-20221014.072055.675.log.

**Comment by liushilongbuaa** [comment]
Retry didn't help

**Comment by jketema** [comment]
Hi @liushilongbuaa. Did you close this issue by accident, or did you figure out what was going on?

**Comment by liushilongbuaa** [comment]
Hi @jketema, I am still testing. My repo is forked from A repo.
A repo enabled LGTM. But my repo didn't enable LGTM. Maybe the error says I didn't have a database?

**Comment by liushilongbuaa** [comment]
I tried it in A repo. It still failed.

**Comment by jketema** [comment]
I don't have quite enough to go on. Are you trying to set up a CodeQL workflow on a forked repo? If so, could you share your workflow configuration?

**Comment by liushilongbuaa** [comment]
> I don't have quite enough to go on. Are you trying to set up a CodeQL workflow on a forked repo? If so, could you share your workflow configuration?

https://github.com/sonic-net/sonic-buildimage/pull/12403
here is my PR.

**Comment by jketema** [comment]
Thanks for the additional info. I don't immediately see any problems with the workflow.

Could you rerun the workflow with debugging enabled, as described [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#creating-codeql-debugging-artifacts)? And could you add the artifacts that will then be created to this issue?

**Comment by liushilongbuaa** [comment]
like this: https://github.com/sonic-net/sonic-buildimage/pull/12404?

**Comment by jketema** [comment]
Yes, that seems correct.

**Comment by liushilongbuaa** [comment]
Hi @jketema , do you need any more info?

**Comment by jketema** [comment]
Yes, I need the artifact the was created during the workflow run. Can you post it here? I don't have access to the artifacts on your workflows.

**Comment by liushilongbuaa** [comment]
what is artifact?

**Comment by jketema** [comment]
At the bottom of the workflow run you should be able to see links to one or more files. Those are what I'm interested in.

**Comment by liushilongbuaa** [comment]
It is 177MB. Can I email to you?

**Comment by jketema** [comment]
Let me check internally what we need to further diagnose this. It's probably only certain files from the artifact that we need.

**Comment by liushilongbuaa** [comment]
[2022-10-14 08:56:49] Spawning plumbing command: execute queries -J-Xmx2960M --off-heap-ram=2960 --verbosity=progress+ --logdir=/home/runner/work/_temp/codeql_databases/python/log --min-disk-free=1024 --evaluator-log-level=5 --threads=2 --insecurely-execute-ml-model-checksums= --warnings=show --additional-packs=/home/runner/work/_temp/github/codeql/main --qlconfig-file=/home/runner/work/sonic-buildimage/sonic-buildimage/qlconfig.yml --output=/home/runner/work/_temp/codeql_databases/python/results -- /home/runner/work/_temp/codeql_databases/python/db-python /home/runner/work/_temp/codeql_databases/python-queries-custom-0.qls
[2022-10-14 08:56:55] [ERROR] Spawned process exited abnormally (code 2; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/tools/linux64/java/bin/java, -Xmx2960M, -Djava.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib, -cp, /opt/hostedtoolcache/CodeQL/0.0.0-20220923/x64/codeql/tools/codeql.jar, com.semmle.cli2.CodeQL, env_argv, execute, queries, -J-Xmx2960M, _, _, _, _, _, _, _, _, _, _, _, --, /home/runner/work/_temp/codeql_databases/python/db-python, /home/runner/work/_temp/codeql_databases/python-queries-custom-0.qls])
[2022-10-14 08:56:55] Plumbing command codeql execute queries terminated with status 2.
[2022-10-14 08:56:55] Exiting with code 2

**Comment by jketema** [comment]
I've checked internally, and there's a small version problem. Your action uses CodeQL 2.11.0, while your [config file](https://github.com/sonic-net/sonic-buildimage/blob/2c141e3817309aef6a70ae4bf21b84259e02bfae/.github/codeql/codeql-config.yml#L3-L4) specifies that the most up-to-date CodeQL libraries should be used. Unfortunately, these are not compatible.

The solution is to replace:
```
  - uses: github/codeql/python/ql/src/codeql-suites/python-code-scanning.qls@main
  - uses: github/codeql/python/ql/src/codeql-suites/python-lgtm-full.qls@main
```
by
```
  - uses: python-code-scanning.qls
  - uses: python-lgtm-full.qls
```

**Comment by jketema** [comment]
Apologies the solution I posted above does not actually work, so I removed it.

Is there a particular reason you added
```
  - uses: github/codeql/python/ql/src/codeql-suites/python-code-scanning.qls@main
  - uses: github/codeql/python/ql/src/codeql-suites/python-lgtm-full.qls@main
```
to the config file?

**Comment by liushilongbuaa** [comment]
> Apologies the solution I posted above does not actually work, so I removed it.
> 
> Is there a particular reason you added
> 
> ```
>   - uses: github/codeql/python/ql/src/codeql-suites/python-code-scanning.qls@main
>   - uses: github/codeql/python/ql/src/codeql-suites/python-lgtm-full.qls@main
> ```
> 
> to the config file?

The default checks are not enough. It has only 38 secure-related checks. LGTM checks about 170 queries.

**Comment by jketema** [comment]
> The default checks are not enough. It has only 38 secure-related checks. LGTM checks about 170 queries.

This is not correct: `security-extended` has 45 queries and `security-and quality` has 167. The only difference between `lgtm-full` and `security-and quality` is some metics related queries, there's no difference in either the security or quality queries that are run.

**Comment by liushilongbuaa** [comment]
Oh, python-code-scanning has 38 queries. And default value is python-code-scanning.
I will add security-and-quality/security-extended, and test again.
Thanks!

**Comment by jketema** [comment]
Note that it's there already: https://github.com/sonic-net/sonic-buildimage/blob/2c141e3817309aef6a70ae4bf21b84259e02bfae/.github/codeql/codeql-config.yml#L5

**Comment by jketema** [comment]
@liushilongbuaa Looking at your open PRs it looks like you fixed the issue. Is that correct?

**Comment by liushilongbuaa** [comment]
it looks good now.

**Comment by liushilongbuaa** [comment]
Hi @jketema, can you help take a look https://github.com/liushilongbuaa/sonic-buildimage/pull/123
Why alerts are detected, but PR checks passed?

**Comment by jketema** [comment]
PR failure depends on the severity level of the alerts. At which severity level failure should happen is configurable: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure

**Comment by liushilongbuaa** [comment]
Thanks a lot!
