### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by sadikkuzu** [github/codeql-action#1305]
https://github.com/github/codeql-action/blob/297ec80a468c234608046f51ee8c65da128a1e94/lib/analyze-action.js#L175-L179

---

**Warning**: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

---

[![image](https://user-images.githubusercontent.com/23168063/196009059-8bab4c0a-ed6d-4a57-b788-afe6af7cc2f9.png)](https://github.com/tugrulcan/havhav/actions/runs/3257242598/jobs/5348386297)

**Comment by jketema** [comment]
This was fixed in https://github.com/github/codeql-action/pull/1301, and will be available in the next release of the action `v2` action (or you can use `main` directly).
