### ISSUE TITLE
Support upload of large databases (> 2GB)

### ISSUE THREAD

**Issue by aibaars** [github/codeql-action#1383]
Currently the codeql-action crashes when trying to upload a CodeQL database bundle that is larger than 2GB. This is because the codeql-action tries to load the entire zip file into a Buffer which is limited to 2GB in Javascript. 

We should probably rewrite: https://github.com/github/codeql-action/blob/4fddc51e4f3b5e5e9022f35c3464736cc10e1e98/src/database-upload.ts#L43-L45

and supply the payload to the `POST` request as a streaming input.

```
Creating zip file at C:\a\_temp\codeql_databases\csharp.zip.
Error: File size (8048141762) is greater than 2 GB
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (8048141762) is greater than 2 GB
    at new NodeError (node:internal/errors:371:5)
    at tryCreateBuffer (node:fs:419:13)
    at Object.readFileSync (node:fs:464:14)
--->at uploadDatabases (C:\a\_actions\github\codeql-action\v2\lib\database-upload.js:51:28)<---
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (C:\a\_actions\github\codeql-action\v2\lib\analyze-action.js:184:9)
    at async runWrapper (C:\a\_actions\github\codeql-action\v2\lib\analyze-action.js:235:9) {
  code: 'ERR_FS_FILE_TOO_LARGE'
```

**Comment by aeisenberg** [comment]
What is the max db size that turboscan can handle?

**Comment by rneatherway** [comment]
Turboscan doesn't currently see the databases. The upload is proxied to Azure Blob storage (via Memory Alpha) by a Go service just as happens with GitHub Releases. The limit is likely to be 5GB due to multipart uploads being required above that size.

**Comment by rneatherway** [comment]
We believe that the limit is 5GB due to the need to use multipart uploads above that size. However, we haven't tested around those sizes yet.

**Comment by robertbrignull** [comment]
This particular issue should be fixed now. Though note that uploads of multi-gigabyte databases is still not fully supported, so it will currently fail for other reasons. We'll be working on improving this over time so larger databases can be uploaded.
