### ISSUE TITLE
Code scanning alerts cite files that are not in the repository

### ISSUE THREAD

**Issue by ROMVoid95** [github/codeql-action#1471]
This was not always a problem since it use to show the exact code line from the source file in the repository. But now any code scanning alerts cite files from `build/sources/` directory. Which obviously, are not commited to the repository (when the project is Java of course)

I'm pretty sure this is just a case of me not configuring this correctly,  But why does the report not show the actual file that is in the repository? It should not require me to go into the source and in the event the line contains more than 1 statement guess which one is being reported? I'm at a loss here. Attached is a screenshot of what i'm talking about.
![2023-01-09 03_34_38-Implicit narrowing conversion in compound assignment · Code scanning alert #15 ·](https://user-images.githubusercontent.com/42848897/211278065-f5c4332c-2b7a-47d8-b72a-745017fb0373.png)

**Comment by tausbn** [comment]
Thank you for your question!

Just to clarify the situation, are you saying that Code Scanning is now displaying alerts in files from the `build/sources/` directory (which as you note it is unable to find in the repo), where it would previously display them in the correct files in the repo? (In other words, the alerts suddenly jumped from one file to another.)

Or are you saying that a bunch of _new_ alerts popped up, all on files in `build/sources/` (which again means they are not shown)?

It sounds to me like it's the first case, but I just wanted to make sure. 🙂

**Comment by ROMVoid95** [comment]
Oh right, haha, my apologizes. Probably a good example as to why one should not make a issue report at 3am after hours of trying to read through the doctoral level of github docs on this tool (which is great btw, not to appear hateful against it).

but yes the first part is correct.
I want to say it showed the preview (and the file the alert was found in) from the source file in the repository (src/main/java/**)
and not (build/sources/main/java/**) when using the v1 version. And this new behavior started when the workflow file was updated to use v2. But i cannot at this time confirm this.

**Comment by tausbn** [comment]
No worries. The documentation _can_ be a bit daunting. There are a lot of options to tweak.

Your comment about v1 versus v2 is potentially very useful, so thank you for bringing that up!

Is there any chance you could share the workflow file with us? That might make it easier to pinpoint the exact issue.

**Comment by ROMVoid95** [comment]
sure, it is located [here](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/master-1.12/.github/workflows/code-analysis.yml)

something to note: the inital action that generated the alerts used the same setup just with the previous versions. the alerts are all the same between then and now as well.

**Comment by maruthiaws** [comment]
rsion we need isn't in the toolcache, there isn't yet a nice way to find the 
Could we add a json file in this repo that has mappings from bundle release number to version number or URL? This would be helpful in general for our users since there's no easy way for them to figure out this mapping right now without downloading and running codeql version.

This could go in defaults.json, which we're already updating for each release.

**Comment by maruthiaws** [comment]
rsion we need isn't in the toolcache, there isn't yet a nice way to find the
Could we add a json file in this repo that has mappings from bundle release number to version number or URL? This would be helpful in general for our users since there's no easy way for them to figure out this mapping right now without downloading and running codeql version.

This could go in defaults.json, which we're already updating for each release.

**Comment by tausbn** [comment]
Thank you!

It looks like the alerts moved after the following commit (where you introduced Lombok into the build configuration): https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/459c4f6cd9c6ec090a2d842177dbb1d01d070bc4

In general, Lombok can do strange things, as it moves the source code around during the build.

You could try using the following "delombok" action: https://github.com/advanced-security/delombok
(Before running the build in the `code-scanning.yml` workflow.) It may be able to undo the "Lomboking" that messes things up. 🙂

**Comment by smowton** [comment]
@ROMVoid95 were you able to resolve the issue using delombok?

**Comment by ROMVoid95** [comment]
@smowton  I was not when i added the action provided to my testing repo for this. 

@tausbn In reference to the commit you linked, it's quite interesting to me that they would have moved after that, because lombok did exist in the build script but applied via the `io.freefair.lombok` Gradle Plugin, which did actually add a delomboking task to every SourceSet on build. After removing it that task no longer ran and I just applied lombok through Dependencies.

however, reverting that commit to the build.gradle file on the test repo resulted in the same outcome so, I will just go ahead and test the build with all lombok removed and will adjust the source code accordingly and see what that does.

**Comment by smowton** [comment]
@ROMVoid95 please confirm whether that works for you so we know if we can close the issue, or if there are other related problems to look at here

**Comment by ROMVoid95** [comment]
To be honest, trying this with all lombok removed would be more work than I am willing to throw at this as alot of the code relies on Lombok and would require a lot of rewrite. I'm just going to say this issue that arose is indeed caused by Lombok and not a CodeQL issue. You can go ahead and close this issue

**Comment by smowton** [comment]
Okay, thanks for following up.

**Comment by smowton** [comment]
There is work afoot to automatically de-Lombok by the way -- it's a difficult task because of how Lombok works, so it may prove infeasible and we can't be sure of a timescale yet, but it's on the radar.
