### ISSUE TITLE
Run github/codeql-action/init@v2 points to github/codeql-action/init@v1 url

### ISSUE THREAD

**Issue by jakemckenzie** [github/codeql-action#1495]
I used this [guide ](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/)that you provided to update my github actions that uses codeql. The problem is that when bumping from v1 to v2 it still points to the v1 url when attempting initialize codeql which 404s.

```
Run github/codeql-action/init@v2
Setup CodeQL tools
  Looked for CodeQL bundle in github/codeql-action on https://github.wmt.services but got error HttpError: Not Found.
  Downloading CodeQL tools from https://github.com/github/codeql-action/releases/download/codeql-bundle-2022[12]( *url left out intentionally* )11/codeql-bundle-linux64.tar.gz. This may take a while.
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/azureuser/actions-runner/_work/_temp/99df6568-fdef-4fb0-a1cb-3fed0dac3c57 -f /home/azureuser/actions-runner/_work/_temp/5a9cde34-e037-40e7-82b6-d57cc2ca1e12
  Error: Error: ENOSPC: no space left on device, copyfile '/home/azureuser/actions-runner/_work/_temp/99df6568-fdef-4fb0-a1cb-3fed0dac3c57/codeql/cpp/tools/linux64/extractor-static' -> '/home/azureuser/actions-runner/_work/_tool/CodeQL/0.0.0-20221211/x64/codeql/cpp/tools/linux64/extractor-static'
  Error: Unable to download and extract CodeQL CLI
  Error: Unable to download and extract CodeQL CLI
      at setupCodeQL (/home/azureuser/actions-runner/_work/_actions/github/codeql-action/v2/lib/codeql.js:301:[15](*url left out intentionally*))
      at async initCodeQL (/home/azureuser/actions-runner/_work/_actions/github/codeql-action/v2/lib/init.js:35:38)
      at async run (/home/azureuser/actions-runner/_work/_actions/github/codeql-action/v2/lib/init-action.js:98:34)
      at async runWrapper (/home/azureuser/actions-runner/_work/_actions/github/codeql-action/v2/lib/init-action.js:[17](*url left out intentionally*)9:9)
```

Not sure what I can do the alleviate this from my end and I thought I would bring it to your attention. Thank you.

**Comment by aeisenberg** [comment]
Thanks for reporting your error. It looks like there are two things going on here:

1. The requested version of codeql is not available on your runner and so the version is being downloaded
2. There is not enough room on your runner and so it can't be unzipped.

However, I do not see a 404 error here. It looks like you are using a self-hosted runner. Are you running on github.com or are you using GHES?

**Comment by jakemckenzie** [comment]
We're using github. I'll talk to the maintainer of the repository about increasing the size for our runner to unzip. My mistake on the 404, the error message was adding a period to the end tar file which I did not notice when I clicked the link [https://github.com/github/codeql-action/releases/download/codeql-bundle-20221211/codeql-bundle-linux64.tar.gz.](https://github.com/github/codeql-action/releases/download/codeql-bundle-20221211/codeql-bundle-linux64.tar.gz.) instead of [https://github.com/github/codeql-action/releases/download/codeql-bundle-20221211/codeql-bundle-linux64.tar.gz](https://github.com/github/codeql-action/releases/download/codeql-bundle-20221211/codeql-bundle-linux64.tar.gz)

**Comment by aeisenberg** [comment]
And if it is self-hosted, then be aware that nothing is automatically cleaned up after a workflow run. So the runner may be due for a manual cleanup. It's is best practice to clean before and after any workflow run on a self-hosted runner.

**Comment by jakemckenzie** [comment]
Thank you, I think you answered my questions quite well.
