### ISSUE TITLE
Support for locally present bundles

### ISSUE THREAD

**Issue by esbena** [github/codeql-action#154]
I would like to run code-scanning with a custom code-scanning bundle
that already is present on my local disk.  I can currently do that by
making the following hack:

### 1 Install bundle in tool cache:

Use `toolCache.cacheDir` to install the bundle with a specially crafted ID:

```js
tc.cacheDir(localBundlePath, 'CodeQL', "0.0.0-XXX-DUMMY-BUNDLE-ID");
```

### 2 Convince codeql to look in the tool cache:

The codeql action is then invoked with a dummy URL that will make codeql.ts lookup the bundle with the specially crafted ID:

```yaml
        ...
        tools: dummy://codeql-bundle-XXX-DUMMY-BUNDLE-ID/dummy
        ...
```

---

This works, but I would like a more reliable solution.  I am not sure
what the best approach is for supporting my use case, but I am happy
to look into implementing a suggestion.

**Comment by aibaars** [comment]
I think the `tools:` property could be made to allow `file://` URL.

**Comment by edoardopirovano** [comment]
Agreed, this is something we also need for https://github.com/github/codeql-coreql-team/issues/1264 so I will be looking at it in the near future.
