### ISSUE TITLE
StringData not declared by package unsafe

### ISSUE THREAD

**Issue by timandy** [github/codeql-action#1546]
go1.20 runtime report `StringData not declared by package unsafe`

https://github.com/timandy/routine/actions/runs/4222282655

Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/debuglog.go:296:20: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/heapdump.go:159:37: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/heapdump.go:202:32: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/heapdump.go:204:32: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/proc.go:658:16: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/runtime.go:115:33: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/string.go:105:17: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/string.go:[115](https://github.com/timandy/routine/actions/runs/4222282655/jobs/7330843706#step:5:116):16: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/string.go:121:39: StringData not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/string.go:163:16: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/string.go:268:16: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/type.go:465:16: String not declared by package unsafe
  Error: 2023/02/20 10:13:31   /opt/hostedtoolcache/go/1.20.1/x64/src/runtime/type.go:474:16: String not declared by package unsafe

**Comment by jketema** [comment]
Hi @timandy, Thanks for opening this issue. I've relayed this to the relevant engineering team for them to have a look at this.

**Comment by timandy** [comment]
@jketema Thanks a lot.
