### ISSUE TITLE
codeql-action/upload-sarif@v2 - invalid URI was provided as a SARIF location

### ISSUE THREAD

**Issue by janchristian-haddorp** [github/codeql-action#1553]
**Invalid URI was provided as a SARIF location**

Our project is using Dockerfile based on Nginx:
```
FROM nginx:1.23.3-alpine
```

When uploading Prisma Cloud scan result using codeql-action/upload-sarif@v2 there is an error. Other Dockerfile with different image naming (e.g. azul/zulu-openjdk:17.0.6-17.40.19-jre) can be processed without any problems.

```
Error: Code Scanning could not process the submitted SARIF file:   
  
an invalid URI was provided as a SARIF location: parse "Dockerfile (nginx:1.23.3-alpine lines:1-1 (sha256:2bc7edbc3c))": first path segment in URL cannot contain colon, an invalid URI was provided as a SARIF location: parse "Dockerfile (nginx:1.23.3-alpine lines:1-1 (sha256:2bc7edbc3c))": 
```

**Comment by aeisenberg** [comment]
Thank you for raising this issue. The problem is that there is an invalid URI being generated by the tool (Prisma Cloud?) that produces the SARIF. The proper fix could only be made by that tool. To work around this, you can try post-processing the SARIF and changing any invalid URI to something parseable.

**Comment by janchristian-haddorp** [comment]
Thanks for quick reply. Yes, SARIF report was generated by Prisma Cloud. Manually patching the JSON sounds not really good...

```
"locations": [
  {
    "physicalLocation": {
      "artifactLocation": {
        "uri": "Dockerfile (nginx:1.23.3-alpine lines:1-1 (sha256:2bc7edbc3c))"
      },
      "region": {
        "startLine": 1,
        "endLine": 1
      }
    }
  }
]
```

**Comment by janchristian-haddorp** [comment]
Fixed now.
