### ISSUE TITLE
Code Scanning could not process the submitted SARIF file

### ISSUE THREAD

**Issue by atodorov** [github/codeql-action#1558]
CodeQL / Analyze (javascript) (pull_request) - https://github.com/gluwa/creditcoin/actions/runs/4322552063/jobs/7545102968 - reports the error in subject

CodeQL / Analyze (javascript) (dynamic)  - https://github.com/gluwa/creditcoin/actions/runs/4322551843/jobs/7545102914 - reports PASS. 

Both of these jobs are coming from the same PR https://github.com/gluwa/creditcoin/pull/957. 

The error is something recent. You can see the same 2 jobs passing a week before on this PR/commit https://github.com/gluwa/creditcoin/pull/939/commits. 

Does anyone know what this error message means and how to go about fixing it ?

**Comment by hmakholm** [comment]
This looks like you _both_ have an explicit CodeQL workflow in your repo _and_ have enabled the [default CodeQL setup](https://github.blog/2023-01-09-default-setup-a-new-way-to-enable-github-code-scanning/).

You cannot use both of these at the same time; that confuses our backend. You shouldn't _need_ to use both of them at the same time either -- the main benefit of the default setup is that it frees you from writing a specific workflow file for the repo, but if you have one anyway, you might as well use that for all your analysis.
