### ISSUE TITLE
The github/codeql-action/analyze@v2 sometimes occured "Error: commit not found"

### ISSUE THREAD

**Issue by AnnAngela** [github/codeql-action#1591]
Hey guy, thanks for your time.

I have a [reuse workflow](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/6087f9395461a2bac6d592d698ace64c8967696b/.github/linter%20test/action.yaml#L42) that run codeQL, and this reuse workflow is called by other workflow.

Sometimes, I got an error message said "Error: commit not found" when other workflow called the reuse workflow. These happened when the top workflow is triggered via schedule ([log1](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4458369050/jobs/7830112154#step:14:2503), [log2](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4463891152/jobs/7839536574#step:14:2503)) or push ([log](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4460840257/jobs/7834249946#step:38:2503)), so I think maybe this error is not relative with the event payload.

But this error is not occured everytime, and I cannot find out the pattern.

Can you help me to identify the problem?

**Comment by aibaars** [comment]
@AnnAngela Thanks for reporting this issue. At first sight I can't see anything wrong with the logs. We'll try to investigate further.


When uploading results, the codeql-action uses the `GITHUB_REF` and `GITHUB_SHA` values by default for the branch and commit parameters. https://github.com/github/codeql-action/blob/fb75ebd7508a284201f74f4bbc92dfd6895ae7da/upload-sarif/action.yml#L16-L21 . As a workaround you may try setting `ref: ${{ github.ref }}` and `sha: ${{ github.sha }}` fields explicitly. I don't think it will make much of a difference, but it might make debugging easier.

**Comment by dbartol** [comment]
@AnnAngela As @aibaars said, we suspect this problem has something to do with the SHA or ref used to upload the SARIF file being different from the values in the event payload. Would it be possible to add a step to your composite action, right before the ` Perform CodeQL Analysis` step, to print out the values of `GITHUB_SHA` and `GITHUB_REF`? That way we can compare to the values used for the `actions/checkout` step in the workflow, which we can already see in the log.

**Comment by AnnAngela** [comment]
@aibaars @dbartol Hi, thanks for you replies. I made a debug output at [here](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4474811736/jobs/7863634523#step:14:1105), and it looks fine:
```shell
$ echo "Github context:" && echo "    ref: ${{ github.ref }}" && echo "    sha: ${{ github.sha }}" && echo "env:" && echo "    ref: $GITHUB_REF" && echo "    sha: $GITHUB_SHA"

Github context:
    ref: refs/heads/master
    sha: 09f521b4748acea73490c8b0d68013241965ecca
env:
    ref: refs/heads/master
    sha: 09f521b4748acea73490c8b0d68013241965ecca
```

**Comment by aibaars** [comment]
That looks all good. Looking into the log a bit more I found this [line](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4474811736/jobs/7863634523#step:8:1472):
```
[2023-03-21T02:07:40.456+00:00] [createCommit] commit_sha: 77caa45d5dabcbc782316a5e9a8f42518495b19a
```
Could you also run `git log -1` in the debug step. Perhaps the workflow is analyzing a different commit than the one specified in `github.sha`.

**Comment by AnnAngela** [comment]
@aibaars Your idea worked, the [log](https://github.com/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/actions/runs/4477113578/jobs/7868244632#step:14:1136) indicated that the workflow is analyzing a different commit.

Is it inappropriate to create a commit in the workflow?

**Comment by aibaars** [comment]
> Is it inappropriate to create a commit in the workflow?

It's fine, however, the commit should be pushed to the repository before uploading the SARIF file with the results. Codescanning uses the commit SHA to fetch file contents when displaying results, so the commit should exist. I see you have a `push` step at the end of the workflow. You could move that step before the `codeql-action/analyze` step, or if you wish to perform the `push` only if all analyses succeed, then you could disable results uploading in the `codeql-action/analyze` step and add a `codeql-action/upload-sarif` step after the `push`.

**Comment by AnnAngela** [comment]
@aibaars Hi, I’m sorry to bother you, but if I create a commit in a workflow, how do I specify the `ref` and `sha` parameters from that commit for CodeQL?

**Comment by AnnAngela** [comment]
> > @aibaars Hi, I’m sorry to bother you, but if I create a commit in a workflow, how do I specify the `ref` and `sha` parameters from that commit for CodeQL?
> 
> I think there is no need to specify the `sha` because by default the codeql-action takes the SHA by looking at the `HEAD` commit. This behaviour isn't documented properly, but should be soon.
> 
> If you want to specify the SHA you could add a step to your workflow that sets an environment variable (eg `NEW_COMMIT_SHA`) and add `sha: ${{ env.NEW_COMMIT_SHA }}` . Instead of an environment variable you can also use a step output variable.

Thank you! I just want to ensure that the workflow still works even if the default behavior of codeql fetching the sha from the local `HEAD` commit changed.

Should I close this issue now?

**Comment by lisafabian19** [comment]
Igot to go, if there a issue make it work and we will fix the alternative issues it's a work program training  before deployment for all type of people and also class for new science biologic animals before arrival a class
________________________________

**Comment by aibaars** [comment]
> Thank you! I just want to ensure that the workflow still works even if the default behavior of codeql fetching the sha from the local `HEAD` commit changed.

I understand. I think it is not very likely that the behaviour of fetching the SHA from the `HEAD` commit will change, but it could happen. Complicating your workflow definition to protect against changes that may never happen is may not be worth the trouble. 

> Should I close this issue now?

Yes let's close this now.

**Comment by AnnAngela** [comment]
> > Thank you! I just want to ensure that the workflow still works even if the default behavior of codeql fetching the sha from the local `HEAD` commit changed.
> 
> I understand. I think it is not very likely that the behaviour of fetching the SHA from the `HEAD` commit will change, but it could happen. Complicating your workflow definition to protect against changes that may never happen is may not be worth the trouble. 
> 
> > Should I close this issue now?
> 
> Yes let's close this now.

You are right. I wrote it down in my notebook instead.
