### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by rsdmike** [github/codeql-action#1606]
![image](https://user-images.githubusercontent.com/22204562/227638058-bc254923-498d-45f2-884f-67a1dbdc8597.png)
Text format of error message:
```
Run github/codeql-action/init@v2
Setup CodeQL tools
  Did not find CodeQL tools version 2.12.5 in the toolcache.
  Downloading CodeQL tools from https://github.com/github/codeql-action/releases/download/codeql-bundle-20230317/codeql-bundle-linux64.tar.gz. This may take a while.
  certificate has expired
  Waiting 17 seconds before trying again
  certificate has expired
  Waiting 14 seconds before trying again
  Error: Error: certificate has expired
  Error: Unable to download and extract CodeQL CLI
  Error: Unable to download and extract CodeQL CLI
      at setupCodeQL (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:140:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async initCodeQL (/home/runner/work/_actions/github/codeql-action/v2/lib/init.js:46:76)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/init-action.js:127:34)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/init-action.js:2[10](https://github.com/open-amt-cloud-toolkit/ui-toolkit-angular/actions/runs/4515244566/jobs/7952299529?pr=537#step:3:11):9)
```

the codeql yaml file can be found here: https://github.com/open-amt-cloud-toolkit/ui-toolkit-angular/blob/2ebe220ae42b49870b8fea9fb2e472a1956229de/.github/workflows/codeql-analysis.yml 

Any help would be greatly appreciated!

**Comment by adityasharad** [comment]
Thank you for raising this, and apologies for the inconvenience. We (GitHub) are aware of TLS problems related to an expired certificate in our CDN configuration, which in this case are affecting the ability to download the CodeQL tools from GitHub Releases. We are working to resolve this issue: updates will be posted to https://www.githubstatus.com/incidents/x7njwb481j9b.

**Comment by adityasharad** [comment]
Update: we expect this issue to be resolved, and have observed CodeQL code scanning runs succeeding again. Please rerun your failing workflows and let us know if you still encounter any trouble. I'll leave this issue open a little longer to help inform others who may have encountered the same error.

**Comment by rsdmike** [comment]
Seems to be working again. Thank you! Closing this issue.
