### ISSUE TITLE
CodeQL Action error: invalid source release: 17

### ISSUE THREAD

**Issue by mudasar187** [github/codeql-action#1611]
My workflow make a CodeQL but it fails on Autobuild command by error `error: invalid source release: 17`. https://github.com/navikt/sokos-pdl-proxy/actions/runs/4533719188/jobs/7986911677#step:5:93.
I followed documentation and its says if the Autobuild command fail, I can replace with my own command:

```
# Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #     make bootstrap
      #     make release
```
So i replaced the command with this custom command:

```
      - name: Autobuild
        run: |
          ./gradlew clean build shadowJar
```

But it still fails. Is this a bug or am I missing something?

**Comment by aeisenberg** [comment]
It looks like you are using Java and you have not set up the correct JDK to build your code. See the [actions/setup-java](https://github.com/actions/setup-java) action. Add the step before you run `codeql-action/init`. You can use this action to make sure that the workflow job uses the correct java version for your build.

**Comment by mudasar187** [comment]
Wierd. Because I have the same workflow in 2 another repo and it works. https://github.com/navikt/sokos-ktor-template/blob/master/.github/workflows/security.yaml. This one I have not defined JDK to build my code before `codeql-action/init` ? I can try set as you says, but do I really need to define it when its works without?

**Comment by aeisenberg** [comment]
I'm not sure. I think this is the easiest fix to try first. If this doesn't work, I'll take a deeper look.

**Comment by mudasar187** [comment]
It works :) Thank you :)
