### ISSUE TITLE
SARIF file not uploaded. But there is no issue.

### ISSUE THREAD

**Issue by DJDuque** [github/codeql-action#1614]
I set-up the `upload-sarif` action a while ago for my repository, and it was all working without any issue. Today, I was expecting a job to fail and upload a SARIF file with my warnings, but nothing happened.

[This is the pull request](https://github.com/DJDuque/alpha-g/pull/65) in question. I have [this GitHub Action](https://github.com/DJDuque/alpha-g/actions/runs/4539507576/jobs/7999608740) which should have detected a `clippy` warning and upload the SARIF file. You can see [here](https://github.com/DJDuque/alpha-g/actions/runs/4539507576/jobs/7999608740#step:4:9) that the warning was written to the `clippy-results.sarif` file.

Finally, you can see [here](https://github.com/DJDuque/alpha-g/actions/runs/4539507576/jobs/7999608740#step:5:43) that the SARIF file was presumably uploaded, but there are no scanning alerts in the PR.

An example of a PR where this was working properly is [here](https://github.com/DJDuque/alpha-g/pull/51). This is the type of warning I was expecting, but I see nothing.

Can someone help me understand what is going on here?

**Comment by aibaars** [comment]
The alerts are listed here though https://github.com/DJDuque/alpha-g/security/code-scanning?query=pr%3A65+tool%3Aclippy+is%3Aopen so the upload must have worked.

I think the problem is that the `detector/src/padwing.rs` file wasn't changed in the analyzed pull request.

**Comment by DJDuque** [comment]
Thanks, I completely missed that.

Feel free to close this issue now that the situation is clear, unless this is not the expected behavior (although it makes sense to me now).
