### ISSUE TITLE
alerts are getting closed as fixed without doing any fix

### ISSUE THREAD

**Issue by yedpodtrzitko** [github/codeql-action#1644]
hi,
I'm trying to setup CodeQL for one project, however the behaviour is somehow unpredictable and I cant figure out why. Googling nor reading docs didnt give me any hint.

### performed steps:

- workflow action is setup for `push` to default branch
  - https://github.com/yedpodtrzitko/godot/blob/master/.github/workflows/codeql.yml

- pushing workflow file into default branch -> first workflow run: 
  - some errors were discovered in the code and reported as alerts ( works as expected )
- amend changes & force push into workflow file -> another workflow run: 
  - previously reported alerts are now marked as fixed without any actual fix (<- **unexpected behaviour**)
  - https://github.com/yedpodtrzitko/godot/security/code-scanning?query=is%3Aclosed+branch%3Amaster
  - it behaves the same even with a regular (non-force/non-amend) push

expected behaviour:
- alerts are not marked as fixed unless there are actual fixes in code performed

another observation:
- making change in any file re-inspect it and previously reported & wrongly-fixed alerts in given file are re-opened again.

**Comment by aibaars** [comment]
Comparing the following runs:
* https://github.com/yedpodtrzitko/godot/actions/runs/4663957767
* https://github.com/yedpodtrzitko/godot/actions/runs/4666139497

I see a large difference in analysis time and the lines of code in database metrics:
```
|                         Metric                         |  Value  |
+--------------------------------------------------------+---------+
| Total lines of user written C/C++ code in the database | 2106483 |
| Total lines of C/C++ code in the database              | 5448432 |
```
vs
```
|                         Metric                         | Value |
+--------------------------------------------------------+-------+
| Total lines of user written C/C++ code in the database |    16 |
| Total lines of C/C++ code in the database              |   912 |
```

It looks like a lot less code was analysed in the second case, which would explain why so many alerts were "lost". 

The large difference in reported times for the "autobuild" step (1h18m vs 51s) suggest that the build step is compiling a lot less code. Likely, because you are using a build cache.

**Comment by yedpodtrzitko** [comment]
thanks for answer.

> Likely, because you are using a build cache.

Yes there is a build cache. So to sum it up: build cache cant be used, otherwise the cached files are ignored/skipped, right?

**Comment by aibaars** [comment]
> Yes there is a build cache. So to sum it up: build cache cant be used, otherwise the cached files are ignored/skipped, right?

Yes, that is correct.

**Comment by yedpodtrzitko** [comment]
ok, kinda' obvious in hindsight 🙃 

thanks again
