### ISSUE TITLE
Error : Invalid set of data when created query file

### ISSUE THREAD

**Issue by pr0v3rt** [github/codeql-action#1654]
Hello, I'm beginner of CodeQL.
While I tried to write my first query, I got this error.
At the first when I moved `.ql` file to under starter directory, the `Query module does not have... ` error solved.
But the `Invalid set of data extentions ` error appeared.
And now the first error appeared again, and it's not solved even I create `.ql` file under the starter directory.
 
[Problem specific]
![ql_error](https://github.com/github/codeql-action/assets/108603511/ad94d2b2-e5d6-481c-86b4-90af08243b47)

It occurs when I create `.ql` file, and I have no idea how to fix it.

What I've tried : 
- re-install codeQL
- installed packages specified in `qlpack.yml`
- updating library
- move `.ql` file under the starter directory

Please help me T.T

**Comment by alexet** [comment]
Can you show me the content of your qlpack.yml file in `ql_tutorial`?

**Comment by pr0v3rt** [comment]
> Thanks for quick response!
Yeah I created new directory and then put my `.ql` file in it and then the error solved!
I'll close this issue 🍡
