### ISSUE TITLE
Python 3.12 support?

### ISSUE THREAD

**Issue by ThiefMaster** [github/codeql-action#1933]
After switching my CodeQL pipeline to Python 3.12 it fails with a very obscure error: https://github.com/indico/indico/actions/runs/6454619622/job/17520526767?pr=5978

And indeed, the [docs](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/) do not list Python 3.12 as supported.

**Comment by MathiasVP** [comment]
Hi @ThiefMaster,

Thanks for raising this issue. We are aware of this issue, and we're working on a fix that we expect to be included in the upcoming CodeQL 2.15.0 release (which we will be rolling out on Actions within the next couple of days).
