### ISSUE TITLE
CodeQL fails for Swift scanning

### ISSUE THREAD

**Issue by rnychyporuk-rbi** [github/codeql-action#2019]
We`re workin on  CodeQL Static Application Security Testing (SAST) implementation for a Swift language using GitHub Actions. During this process, I encountered an issue with the CodeQL initialization step when integrating with a Fastlane-based build process.

When including the CodeQL initialization step (github/codeql-action/init@v2) in the GitHub Actions workflow before Fastlane-based build commands, the build job fails with a CodeSign error. The specific error message indicates that the CodeSign command has failed.

Interesting Behavior: if I remove the CodeQL initialization step from the GitHub Actions workflow, the build application process works perfectly without any issues - application builds well.

**Comment by smowton** [comment]
Can you save and share a full log from the build that produced this error?

**Comment by aeisenberg** [comment]
It would be useful to re-run in [debug mode](https://github.blog/changelog/2022-08-01-debugging-codeql-analysis-in-code-scanning-made-easier-by-obtaining-detailed-logs-and-debugging-artifacts-from-the-codeql-action/) and share the logs from that run.

**Comment by rnychyporuk-rbi** [comment]
Closing an issue as Debug logs can`t be provided for external resources.
