### ISSUE TITLE
[v2.22.11] Workflow verification failed: imposter commit

### ISSUE THREAD

**Issue by secustor** [github/codeql-action#2040]
Since we upgraded our codeql actions from [`2.22.10` to `2.22.11`](https://github.com/renovatebot/renovate/pull/26284/files) we are getting errors in `upload-sarif`. 

<img width="766" alt="image" src="https://github.com/github/codeql-action/assets/17493763/a97b3660-74d3-40f6-8e67-4510fd74ab3f">

https://github.com/renovatebot/renovate/actions/runs/7202046717/job/19619416612#step:4:1217
```
2023/12/13 22:56:21 error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: imposter commit: 03e7845b7bfcd5e7fb63d1ae8c61b0e791134fab does not belong to github/codeql-action/upload-sarif, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}
```

Looking at the changes between the two tags, [they are looking quite big for a patch](https://github.com/github/codeql-action/compare/v2.22.10...v2.22.11). Maybe creating this tag has been an accident? 

Thanks for your help!

**Comment by aibaars** [comment]
Thanks for reporting! That is curious, the commit seems to exist https://github.com/github/codeql-action/commit/03e7845b7bfcd5e7fb63d1ae8c61b0e791134fab . Is this some temporary problem? Have you tried to re-run the workflow?

The [patch](https://github.com/github/codeql-action/compare/v2.22.10...v2.22.11) looks quite large indeed, but it seems to be mainly changes test files, CI scripts, and comments.

**Comment by secustor** [comment]
It occurs consistently in the last ~20 pipelines all today and yesterday. 
So I would not expect it to be some temporary problem.

**Comment by pandatix** [comment]
Same thing here three days later, there is still a message of the imposter commit.

**Comment by aeisenberg** [comment]
As @aibaars suggests, the ossf/scorecard-webapp action is going to need to change how they special case codeql-action so that they can allow v2 to go through since the commit you reference is only in v2. @pandatix have you tried moving to v3?

**Comment by spencerschrock** [comment]
Yes, this is a problem in ossf/scorecard-webapp, not in github/codeql-action. 

I have a short-term fix under review, and once verified will be pushed to our service. It shouldn't require any changes to your workflow. After the holidays, we'll be looking into ensuring this breakage doesn't happen again on major version bumps.

**Comment by spencerschrock** [comment]
This should now be resolved. Apologies for any inconvenience.

> I don't really understand why this is flagged as an "imposter commit". The commit is not part of the default branch (main), but it is part of the releases/v2 branch.

By default, scorecard-webapp's approach was to check for the commit in the repo's default branch (e.g. main for github/codeql-action). The problem with this approach is exactly what we see here, when repos patch their older releases. 

Our choice was mainly due to a limitation of the GitHub API, I'd love for an API that says "does this commit belong to any branch in the repo", but we haven't seen any.

**Comment by pandatix** [comment]
Thanks everyone, the fix seems to work properly :)

**Comment by aeisenberg** [comment]
Thanks everyone for the quick resolution. Closing this issue now.
