### ISSUE TITLE
v3 published without changelog?

### ISSUE THREAD

**Issue by mydea** [github/codeql-action#2059]
Hey, we just got prompted to update from v2 to v3 (see: https://github.com/getsentry/sentry-javascript/pull/10004), but I don't really see any changelog for v3 - is this on purpose? Should v3 already be out?

**Comment by jketema** [comment]
I believe this is on purpose. See the discussion here: https://github.com/github/codeql-action/issues/1959

**Comment by jketema** [comment]
The missing changelog in the dependabot PR seems some dependabot limitation, as [the actual changelog is populated with the relevant changes](https://github.com/github/codeql-action/blob/main/CHANGELOG.md).

**Comment by mydea** [comment]
Ah, I see. IMHO it is a bit confusing to have a new major version that is not reflected in the (Github) releases at all, making it hard to grasp the potential impact of a major upgrade! Just some feedback! Also in the actual changelog, you do see the `3.22.x` release, but no `3.0.0` which is also confusing because I'd usually go look for that to see what breaking changes happend for v3 - hard/impossible to know which `3.x.x` release was the first v3 release without this!

**Comment by jketema** [comment]
I'd suggest you add this feedback to https://github.com/github/codeql-action/issues/1959. I agree this is confusing.

**Comment by mydea** [comment]
Closing this in favor of https://github.com/github/codeql-action/issues/1959, left a comment there as well - thank you!
