### ISSUE TITLE
Error: The configuration file "/home/runner/work/_temp/user-config-from-action.yml" is outside of the workspace

### ISSUE THREAD

**Issue by p5** [github/codeql-action#2145]
As of an hour ago, we have been receiving errors from the `github/codeql-action/init@v3` action with no changes being made on our end.  

This is happening during the "Load language configuration" step.  Please see the below error:

```
  Error: The configuration file "/home/runner/work/_temp/user-config-from-action.yml" is outside of the workspace
```

Since there were no changes on our end, I feel a bug or backwards-incompatible change may have been introduced in a recent commit.  I am looking to see if there's anything obvious I can find.

Edit:
A fix has been proposed :tada: 
https://github.com/github/codeql-action/pull/2147

**Comment by p5** [comment]
Pretty sure it was introduced in this merge PR, but haven't yet identified the main source of the error
https://github.com/github/codeql-action/commit/ece8414c725e29de2e18c0859fda9e7280df9488

**Comment by p5** [comment]
The individual commit appears to be https://github.com/github/codeql-action/commit/191f59f4358411fb10dbfa2ecba95bf51fc6614d which introduced the error

**Comment by p5** [comment]
This code requires the configuration file to be inside the workspace directory before proceeding
https://github.com/github/codeql-action/blob/main/src/config-utils.ts#L886-L902

But this doesn't account for the fact that https://github.com/github/codeql-action/commit/191f59f4358411fb10dbfa2ecba95bf51fc6614d has moved the configuration file outside the workspace, into a temp directory

**Comment by angelapwen** [comment]
Thank you for the notification: we've identified the error and have a fix up https://github.com/github/codeql-action/pull/2147 As soon as it's in `main`, we'll release again to `v2` and `v3`.

**Comment by angelapwen** [comment]
The fix is merged, and we're going through the release process for `v2` and `v3` again. In the meantime, we've already manually retagged `v2` and `v3` to the version prior to the faulty release, so workflows using those tags should already no longer be seeing this issue.

**Comment by angelapwen** [comment]
Thank you also for identifying the commit with the error 😄 we were doing it at the same time internally and you were just as fast!
