### ISSUE TITLE
Recursive SARIF file detection from `upload-sarif` sarif_file parameter

### ISSUE THREAD

**Issue by tlsa** [github/codeql-action#220]
I [created a workflow](https://github.com/tlsa/libcyaml/blob/tlsa/codeql/.github/workflows/static-analysis.yaml#L74) that runs Clang scan-build with the `-sarif` parameter, to output SARIF format, and the `-o build/sarif` argument to put the output in the directory `build/sarif`.

When it is run, scan-build puts the actual SARIF files in a sub-directory of the specified output directory.

The output from scan-build is:

```
scan-build: Analysis run complete.
scan-build: Analysis results (sarif files) deposited in '/home/runner/work/libcyaml/libcyaml/build/sarif/2020-09-18-110804-4323-1'
```

And the sarif files are in the randomly named sub-directory:

```
$ find build/sarif
build/sarif
build/sarif/2020-09-18-110804-4323-1
build/sarif/2020-09-18-110804-4323-1/report-B4xj3N.sarif
build/sarif/2020-09-18-110804-4323-1/report-yK7dxl.sarif
build/sarif/2020-09-18-110804-4323-1/report-SrmlCl.sarif
build/sarif/2020-09-18-110804-4323-1/report-QPrVcF.sarif
build/sarif/2020-09-18-110804-4323-1/report-67tbyT.sarif
build/sarif/2020-09-18-110804-4323-1/report-OfHm5E.sarif
build/sarif/2020-09-18-110804-4323-1/report-T8GZn7.sarif
build/sarif/2020-09-18-110804-4323-1/report-NKjLYw.sarif
build/sarif/2020-09-18-110804-4323-1/report-z81jQ7.sarif
build/sarif/2020-09-18-110804-4323-1/report-bmXRUK.sarif
build/sarif/2020-09-18-110804-4323-1/report-6aH1dl.sarif
build/sarif/2020-09-18-110804-4323-1/report-iK7eHK.sarif
build/sarif/2020-09-18-110804-4323-1/report-vnqcCF.sarif
build/sarif/2020-09-18-110804-4323-1/report-aATCA3.sarif
```

You can see the CI run for this here: https://github.com/tlsa/libcyaml/runs/1133489433

At the moment, with

```
    - name: upload scan-build
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: build/sarif
```

I get the following error:

```
#[error]No SARIF files found to upload in "build/sarif".
Error: No SARIF files found to upload in "build/sarif".
    at Object.upload (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:114:19)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:29:46)
```

Could the `sarif_file` directory parameter be changed to a recursive search through the directory for SARIF files?

**Comment by robertbrignull** [comment]
This sounds like a reasonable change to me. Shouldn't have any unintended side-effects as I highly doubt anyone is currently relying on the behaviour is specifically _not_ being recursive.

**Comment by tlsa** [comment]
Yeah, I hoped that would be the case!

**Comment by chao2zhang** [comment]
Please allow me to share more use cases specifically for Java projects. With a multi-module Gradle project, static analysis tools like [Checkstyle](https://checkstyle.sourceforge.io/version/4.4/config.html) and [Detekt](https://github.com/detekt/detekt/) can generate one or more reports per module. Therefore recursively walking through the directory is fairly common, at least for all gradle projects. I hope this issue can be addressed **soon**.

I did some quick search and it looks like the change is within this function `upload-lib.js` (https://github.com/github/codeql-action/blob/main/lib/upload-lib.js#L69). My Javascript skill is a bit rusty, but I can give it a try if this issue left unattended for a long time.

**Comment by tlsa** [comment]
@chao2zhang Thanks for implementing this!  Confirmed it works with my original clang scan-build output use case.

**Comment by Trass3r** [comment]
Did this make it work for you?

I'm always getting
```sh
  Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more runs than allowed (147 > 15)
  Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more runs than allowed (147 > 15)
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:337:19)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:56:13)
```

**Comment by aeisenberg** [comment]
@Trass3r, please raise a new issue for this. You are seeing a different problem than was originally reported. Your workflow is producing too many sarif runs. You will need to upload them in batches of 15 or less and use a different (but consistent) category name for each upload.

[More information about categories.](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-a-category-for-the-analysis)

**Comment by tlsa** [comment]
@Trass3r Yes, something changed and the server now rejects the SARIF output generated by Clang scan-build.

**Comment by Trass3r** [comment]
scan-build simply produces 1 sarif file per source file.
Even though most are empty 15 is still a pretty low limit.
It can be mitigated a bit via
```sh
npx -y @microsoft/sarif-multitool merge csa/*/*.sarif
```
But I can't say yet whether that really fixes the problem.
