### ISSUE TITLE
Java extractor fails when compiling javac with Bazel

### ISSUE THREAD

**Issue by jasonschroeder-sfdc** [github/codeql-action#2214]
I'd like to use CodeQL on the [bazel-buildfarm](https://github.com/bazelbuild/bazel-buildfarm) repo. I have a WIP PR with a GitHub Action here: https://github.com/bazelbuild/bazel-buildfarm/pull/1688

As this is built with Bazel, I understand I cannot use the autobuilder functionality for compiled languages, as that only supports Maven and Gradle.

I get the following error after `github/codeql-action/init@v3` and during Bazel building:

```
[WARN] Failed to create log file in /home/runner/work/_temp/codeql_databases/java/log

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
[ODASA Javac] Failed to execute ODASA javac builder: java.lang.RuntimeException: Failed to create a unique file in /home/runner/work/_temp/codeql_databases/java/log/ext
Error: Exception in thread "main" java.lang.Error: Fatal extractor error detected. Attempting to abort build commands.
	at com.semmle.extractor.java.interceptors.JavacMainInterceptor.javacMainResult(JavacMainInterceptor.java:53)
	at jdk.compiler/com.sun.tools.javac.main.Main.SEMMLE_INTERCEPT$9(Main.java)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:329)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```
_from https://github.com/bazelbuild/bazel-buildfarm/actions/runs/8462955332/job/23185088050?pr=1688_

I'm not really sure where to go next. Any advice would be terrific! Thank you in advance!

**Comment by jketema** [comment]
Hi @jasonschroeder-sfdc,

Thanks for your question. Note that there are some specific instructions you'll need to follow when building with Bazel. Go to [here](https://docs.github.com/en/enterprise-cloud@latest/code-security/codeql-cli/getting-started-with-the-codeql-cli/preparing-your-code-for-codeql-analysis#specifying-build-commands) and scroll down a bit.

**Comment by jasonschroeder-sfdc** [comment]
Hi @jketema , thanks so much for a reply so quickly!
That fixed it! 🎉 

Would it be possible to copy the Bazel parts to this webpage? I was looking in the wrong place and missed these Bazel-specific instructions.
https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#building-java--and-kotlin

**Comment by jketema** [comment]
Great to hear to it is fixed. I agree that the webpages could be better organised here. The best thing to do is opening an issue in https://github.com/github/docs and explaining the issue. That is, that the section on specifying build commands is also relevant when creating an advanced setup, and that's not clear from the documentation that this is actually the case.

**Comment by jketema** [comment]
To add: note that a copy of the linked pages lives in https://github.com/github/docs.

**Comment by jketema** [comment]
Closing this issue, as this seems resolved now.
