### ISSUE TITLE
Add CodeQL version to github/codeql-action/init outputs

### ISSUE THREAD

**Issue by mschwager** [github/codeql-action#2367]
Hi there,

I'm working on caching some query compilations and it'd be helpful to receive the CodeQL version as output from the `github/codeql-action/init` action. This could be done similar to the `codeql-path` output. It appears that this would require minimal changes in the following locations:

https://github.com/github/codeql-action/blob/b611370bb5703a7efb587f9d136a52ea24c5c38c/src/init-action.ts#L557

Add something like `core.setOutput("codeql-version", await codeql.getVersion()).version)`.

And:

https://github.com/github/codeql-action/blob/b611370bb5703a7efb587f9d136a52ea24c5c38c/init/action.yml#L139-L141

Add something like:

```yaml
   codeql-version: 
     description: The version of the CodeQL binary used for analysis 
```

**Comment by ginsbach** [comment]
Thank you for submitting this issue with the linked PR to fix it!
As the PR is approved, feel free to merge it after resolving the remaining merge conflict.
