### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by aaomidi** [github/codeql-action#24]
https://github.com/microsoft/azuredatastudio/actions/runs/97569453

Trying to enable it for this repository ended up with bad credentials message.

Do I need to do something special to pass the credentials in?

**Comment by robertbrignull** [comment]
Unfortunately there's currently a 1 hour limit on build time. If your workflow takes longer than 1 hour then a token expires and the upload of results fails like this. A fix for this is in the pipeline and should be deployed within a few weeks.

If you can reduce your build time to under 1 hour then that should fix things. I note that all of the times is spent on javascript extraction and analysis. Could you use the `paths` and `paths-ignore` config fields (see https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#specifying-directories-to-scan) to exclude some parts of the repo that you are not interested in? Perhaps there's some generated code or libraries checked in to the repo that can be excluded?

**Comment by robertbrignull** [comment]
Hi, sorry it's taken a long time, but the fix for this issue has now been fully deployed. Jobs can take longer than 1 hour and the update to code scanning won't fail anymore.

**Comment by stoyanov-x** [comment]
@robertbrignull I have a job that takes 1d 18h to complete (yes, it's a huge monorepo but we'd like to see the results of an initial scan result).

What is the current token lifetime? Can that be extended?

<img width="1071" alt="Screenshot 2024-08-25 at 12 35 22 PM" src="https://github.com/user-attachments/assets/2195480a-3601-4956-a71b-177805b32f95">

**Comment by stoyanov-x** [comment]
[Judging by this piece of documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication), the default GitHub Actions job token expires after 24 hours.

**Comment by aeisenberg** [comment]
@stoyanov-x, this is an old issue. Can you please create a new one and someone on the team can help.

If you are having trouble with the default, generated token, you can add a custom token as a repository secret and use that token in the `token` input of the `codeql-action/upload-sarif` action. There are other tricks to try if that doesn't work. We can discuss more in a new issue.
