### ISSUE TITLE
CodeQL Autobuild fails on C# (.NET 5 RC1)

### ISSUE THREAD

**Issue by Reelix** [github/codeql-action#244]
# Steps to replicate the issue

1.) Create a C# Project using the latest Release Candidate of .NET 5
2.) Add CodeQL with the default yml file
3.) Notice CodeQL Fails with "We were unable to automatically build your code."

**Comment by marsen** [comment]
plus

**Comment by Reelix** [comment]
With the release of .NET 5.0, this bug was also effectively fixed.

Add a `global.json` file to your project with the following code

```
{
  "sdk": {
    "version": "5.0.100",
    "rollForward": "latestMajor"
  }
}
```

I have tested this on my own .NET 5.0 project over at https://github.com/Reelix/Reecon and it works.

**Comment by marsen** [comment]
thanks, it's work for me 👍 👍 👍 👍 👍
