### ISSUE TITLE
How do I find the commit hash for a particular version of the codeql-action?

### ISSUE THREAD

**Issue by karianna** [github/codeql-action#2495]
For example, I'd like to be able to use the commit hash when referencing the coedql-action/autobuild action, something like:

`uses: github/codeql-action/autobuild@<hash of commit for the latest version> # v3.26.8`

The releases have the bundle versions, but I'm having a fail at finding the specific hash for the specific action.

**Comment by jketema** [comment]
Hi @karianna,

I'm not completely sure I understand what you mean, but each version corresponds to a tag in the codeql-action repository. For example, for 3.16.8: https://github.com/github/codeql-action/tree/v3.26.8

**Comment by aeisenberg** [comment]
The easiest thing to do is go to the tag in the code section of this repo: https://github.com/github/codeql-action/tree/v3.26.8 and find the associated commit.

Alternatively, if you have `gh` installed:

```
$ gh api --jq '.sha' /repos/github/codeql-action/commits/v3.26.8 
294a9d92911152fe08befb9ec03e240add280cb3
```

**Comment by karianna** [comment]
Thank you both, that worked perfectly!
