### ISSUE TITLE
Consider spacing out the releases

### ISSUE THREAD

**Issue by evelikov** [github/codeql-action#2500]
Above all thanks for the tool team, it is greatly appreciated.

Recently we've enabled CodeQL with hashed checkout alongside dependabot, to keep things up-to date. While we appreciate the updates, the weekly PRs coming for CodeQL with each release having a handful of commits it feels ... a bit too much.

I cannot see any other action out there, which releases so frequently.

May I suggest spacing to a release every 2-4 weeks?

**Comment by aeisenberg** [comment]
If weekly updates are too often for you, then you can consider monthly updates instead. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval This would be for all actions scans. I don't think there's a way to set it for a single repo.

**Comment by smowton** [comment]
It's worth noting there'll only be a few commits *in the action repository*, but the main thing it's doing is upgrading to the newest version of the CodeQL bundles and CLI, which is typically released fortnightly (though recently we had two releases a week apart for exceptional reasons).
