### ISSUE TITLE
Could we recommend a different scheduled build time?

### ISSUE THREAD

**Issue by andymckay** [github/codeql-action#258]
Hi there, the readme in this repository shows a `cron` of `0 0 * * 0` which is 00:00 on Sunday. We get a large spike of runs at the top of every hour because lots of people have copied this value into their Actions. We cope with this by smoothing out the load at that time.

So this possibly the worst time for us and our customers to run this build. Could we avoid this time and come up with a different one please?

**Comment by robertbrignull** [comment]
In the workflows generated by people clicking "set up this workflow" (see screenshot below) the build time is randomly generated within some bounds. So for workflows set up using that method they'll already be moderately distributed.
![set up](https://user-images.githubusercontent.com/3749000/95304446-8aa57c00-087c-11eb-8049-0b296fb0bb45.png)

For this repo we can't do that and I think it would be quite odd to pick a hard-coded random time. We could add a comment into the example workflow asking people to pick a random time to help ease load. How would you explain that?

**Comment by andymckay** [comment]
So glad to hear that using `Set up this workflow` uses a random time. The README  says "To get code scanning results from CodeQL analysis on your repo you can use the following workflow as a template:", so the proposed https://github.com/github/codeql-action/pull/259 ☝🏾 just moves it back by an hour and half to not be at our peak. That way if anyone does copy the workflow instead of using `Set up this workflow` they'll be better off.
