### ISSUE TITLE
Init picks latest v2 although action_ref points to v3

### ISSUE THREAD

**Issue by mbtools** [github/codeql-action#2608]
The workflow is configured with `github/codeql-action/init@662472033e021d55d94146f66f6058822b0b39fd` which is v3.27.0.

However, the action run picks v2.19.3 (latest) to run. 

Why? How do we force it to v3?

Workflow:
https://github.com/verdaccio/verdaccio/blob/master/.github/workflows/codeql-analysis.yml

Action Run:
https://github.com/verdaccio/verdaccio/actions/runs/11845411047/job/33012972377

**Comment by mbtools** [comment]
Thanks for the precise answer 👍

**Comment by mbtools** [comment]
It might be helpful for others to include the action version here:

![image](https://github.com/user-attachments/assets/6f7498d8-bb7e-4a45-b6d8-866c84a61097)

**Comment by jketema** [comment]
> It might be helpful for others to include the action version here:

Thanks for the excellent idea. I'll take this into consideration.
