### ISSUE TITLE
Request to use the `/code-scanning/sarifs` endpoint for sarif upload

### ISSUE THREAD

**Issue by klutchell** [github/codeql-action#2654]
https://github.com/github/codeql-action/blob/9d599696ef6f3546b15e3d9dfe46db6dfa487b9a/src/upload-lib.ts#L334-L341

I'm trying to figure out why this function doesn't use the SARIFS endpoint for uploads, which would allow the use of a GitHub App Installation token for uploads. The endpoint currently in use doesn't validate for GitHub Apps (which is likely why your docs say to use the default token).

https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data
https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-code-scanning-alerts

Is there a particular reason for the use of the `/code-scanning/analysis` endpoint throughout this code base? I can't find any reference to it in the [REST docs](https://docs.github.com/en/rest/code-scanning/code-scanning), and the closest seems to be `/code-scanning/analyses` and `/code-scanning/sarifs`.

**Comment by aeisenberg** [comment]
It's an internal endpoint and it is only enabled for the default actions token. To be honest, I'm not entirely sure of the rationale behind this. I can do some digging if you like. I'd like to understand your use case, though. 

If you really need to use an app token, then you can set the `upload` input to the `analyze` action to `false`. And then in the next step, you can run the `/repos/{owner}/{repo}/code-scanning/sarifs` explicitly using the token you want.

**Comment by klutchell** [comment]
Come context:

> We are using a shared workflow on 100s of repos, and one of the steps is to run [octoscan](https://github.com/synacktiv/action-octoscan) and then call the upload-sarif action.
> 
> [Here](https://github.com/product-os/flowzone/blob/5ddbd8fa1b0148b15f47282601ba10af2433fa2b/flowzone.yml#L1735-L1755) is the relevant code snippet in the shared workflow.
> 
> Where we are running into issues, is our Enterprise enforced permissions for the automatic github token ([restricted](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)) does not include the `security-events` permission,  as required by this step.
> 
> In order to override the default permissions, the calling workflow (not the shared workflow) needs to add the new permission scope. This would be reasonable if we were not in the high 100s of repositories in our enterprise that we want to scan.
> 
> The preferred solution for us is to leverage our existing app for authentication tokens, as we do for most other steps in the shared workflow, but then I ran into errors on the upload-sarif step. Related [PR](https://github.com/product-os/flowzone/pull/1295/files).

It obviously makes more sense for this project to use the automatic github token by default, I was just hoping there was a way it could optionally be used with an installation token to reduce the friction of managing our permissions.

I like the idea of a separate github-script action to perform just the upload, I can give that a try. We are only using the upload-sarif action from here anyway.

**Comment by aeisenberg** [comment]
Please let me know how that works out. Closing this issue, but feel free to re-open if you have any more questions.

**Comment by klutchell** [comment]
Here's what I have for my custom upload step:
https://github.com/product-os/flowzone/pull/1295/files

It seems to be working, what do you think?

**Comment by aeisenberg** [comment]
Looks fine to me. I would have implemented this in a bash script and used the `gh` cli, but `actions/github-script` is just as good.

**Comment by klutchell** [comment]
Thanks for the feedback and the quick responses!
