### ISSUE TITLE
Better integration outside of the Security tab.

### ISSUE THREAD

**Issue by bazzadp** [github/codeql-action#268]
At the moment it appears all the results go to the security tab of the repo and not into any pull request that initiated the scan nor any of the GitHub Action logs.

Is it possible to include the results in the logs?

Is it possible to fail the action if any new issues are found so it clearly shows on pull requests rather than expecting PR reviewers to also remember to check the security tab and switch to the PR branch?

**Comment by robertbrignull** [comment]
> Is it possible to fail the action if any new issues are found so it clearly shows on pull requests rather than expecting PR reviewers to also remember to check the security tab and switch to the PR branch?

It should already create a check run on the pull request and populate annotations there for any new alerts. The check run will also be marked as "failed" so you can use that to block merging of a PR.

Can you link to your repository/workflow? Perhaps it is not set up fully so code scanning is not working on pull requests.

**Comment by bazzadp** [comment]
Thanks for getting back so promptly. Hopefully I'm missing something here and this is already there cause I am super keen to use this.

Here's the example PR, where I enabled this action and caused it to do a full scan of the repo:
https://github.com/bazzadp/almanac.httparchive.org/pull/192

I do see it as as passed:

![Actions Results](https://user-images.githubusercontent.com/10931297/96431435-69894780-11fb-11eb-82c4-271585ea22d1.png)

However I do see Warnings and Notes, in the Security tab:

![image](https://user-images.githubusercontent.com/10931297/96431587-a2292100-11fb-11eb-82a8-0752efe0f762.png)

Yet no mention of these in the PR so how is the PR raiser, or PR review supposed to know there are issues to address?

Does it only block on Errors and not on Warnings and Notes? Luckily I don't have any of those in the code 😀, but it would be nice to know if we'd introduced new Warnings or Notes that were no there previously. Or is that the issue these are not things change in this CR and so existing issues so not flagged in this PR?

Also when I click on details I don't see those Warnings and Notes in the logs - it could be nice if that Details link (or an additional link) linked to the Security tab where it's possible to see the outputs and not just the logs that don't see to give the necessary detail.

Does that make sense?

**Comment by robertbrignull** [comment]
The info is in the [Code scanning results](https://github.com/bazzadp/almanac.httparchive.org/pull/192/checks?check_run_id=1274460674) check that is created by code scanning. The code scanning analysis was successful, but to produce results on the PR code scanning has to compare those results to an earlier so it can say which results are new to that PR and which are existing alerts.
Since this PR is introducing the code scanning workflow there's nothing to compare it to. So for this first PR you don't get any annotations on the PR. For future PRs you'll get notified only when the PR introduces or fixes an alert.
For this first PR you can view the results in the security tab as you've already seen. In the future we'll be able to improve their first-PR experience so it's less confusing.

**Comment by bazzadp** [comment]
Ah perfect, that explains that. I merged it and did another [Test PR](https://github.com/bazzadp/almanac.httparchive.org/pull/194) and can indeed see the results in there and also in the results:

![Code Scanning Results](https://user-images.githubusercontent.com/10931297/96444434-254f7480-1206-11eb-9377-b5320c3af56e.png)

Is it possible to make warnings fail the Github Action? Or it it only errors that do that?

**Comment by robertbrignull** [comment]
> Is it possible to make warnings fail the Github Action? Or it it only errors that do that?

Sorry that isn't configurable at the moment. It's definitely something that will be added in time though.

It looks like all questions are answered now, or at least the initial problem is sorted, so I'll preemtively close this issue.

**Comment by bazzadp** [comment]
Yup, happy to close. Thanks very much for your help!
