### ISSUE TITLE
Remove fail-fast strategy

### ISSUE THREAD

**Issue by konradpabjan** [github/codeql-action#28]
The [fail-fast](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) strategy is currently in the workflow template:

```
    strategy:
      fail-fast: false
```

However, there is only a single job (`ubuntu-latest`) with no matrix so this will have no effect if it's true or false. This yaml snippet should be removed.

**Comment by konradpabjan** [comment]
While on the topic of improving the `yaml`, i would also suggest this snippet:

```
on:
  push:
    paths-ignore:
      - '**.md'
```

If there are changes only to `.md` files then this will prevent the workflow from running. The run can take 4+ minutes on `ubuntu-latest`, so this will reduce unnecessary runs if users are making simple changes.

**Comment by robertbrignull** [comment]
Thanks for pointing that out. I'll open an issue to have the workflow template updated. I'll leave this repo as it is for now as much of the content in the readme in this repo is likely to be removed very soon and replaced with links to documentation and other more centralised examples.

**Comment by LADYBEAR7819** [comment]
> The [fail-fast](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) strategy is currently in the workflow template:
> 
> ```
>     strategy:
>       fail-fast: false
> ```
> 
> However, there is only a single job (`ubuntu-latest`) with no matrix so this will have no effect if it's true or false. This yaml snippet should be removed.

**Comment by robertbrignull** [comment]
It took a little while but the workflow template has now been updated, so this issue is now addressed.
