### ISSUE TITLE
Allow `analyze` and `upload-sarif` actions to be used in the same workflow

### ISSUE THREAD

**Issue by cwong-scw** [github/codeql-action#300]
I would like to request that the [restriction](https://github.com/github/codeql-action/blob/main/src/upload-lib.ts#L197) of only running one of the `codeql/analyze` or `codeql/upload-sarif` actions per job is removed or relaxed to allow for SARIF file pre-processing before uploading. The `codeql/analyze` action supports an `upload` [input](https://github.com/github/codeql-action/blob/main/analyze/action.yml#L12) that enables or disables automatic SARIF upload, which could be used together with a SARIF pre-processor before the `codeql/upload-sarif` action as a final step in a workflow job but the current restriction prevents this.

Our use case for this is to be able to enrich the CodeQL-generated SARIF file(s) with contextual training material before they are uploaded and displayed as Code Scanning alerts but this change would also generically enable other actions to pre-process the SARIF files for other purposes. Would something like this be possible? One approach might be to just disallow repeated use of the _same_ CodeQL action within a workflow.

**Comment by josepalafox** [comment]
@jhutchings1 👀

**Comment by robertbrignull** [comment]
@cwong-scw, the scenario you describe above is already possible. If you pass `upload: false` to the `analyze` action, then you can process the SARIF file and then call the `upload-sarif` action later on and it won't throw any errors.

I'm going to close as I think this is addressed. If the above doesn't work for you please let us know.

**Comment by cwong-scw** [comment]
Thanks @robertbrignull - you are absolutely correct. Not sure what I did wrong in my previous tests. Sorry about that!
