### ISSUE TITLE
semver release tags

### ISSUE THREAD

**Issue by thepwagner** [github/codeql-action#307]
Would it be possible to start tagging semver-compatible releases?

We follow GitHub's [best practice](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions) of pinning our Actions to full length commit SHAs.
We use [Dependabot version updates](https://github.blog/2020-06-25-dependabot-now-updates-your-actions-workflows/) to keep our other Actions up to date. This doesn't work with `github/codeql-action` since there are no released tags.

I think everything would work if there were semver compatible tags (e.g. `v1.0.0`, `v1.1.0` along the `v1` branch).

**Comment by Mogost** [comment]
Faced with the same thing. 
I don't understand why this hasn't been done yet.

**Comment by adityasharad** [comment]
Thanks for the feedback. We started creating `v1.*` [tags](https://github.com/github/codeql-action/tags) from May 2021 onwards and have incorporated them into our regular release process. Workflows may continue to use `v1` to follow the release branch of this Action, or use a specific `v1.*` tag (ideally together with Dependabot version updates as @thepwagner suggests).
I'll close this issue, but please feel free to reopen if the release tags aren't working for you, especially with Dependabot.

**Comment by aliscco** [comment]
Please do not  create anything yet .
How can you confirm the value is correct?
