### ISSUE TITLE
Pull_request.filter is not a function error is thrown when there is a single value defined in on.pull_request.branches

### ISSUE THREAD

**Issue by solita-alperttiti** [github/codeql-action#331]
It seems, that latest commit of actions-utils.js expects on.pull_request.branches to be an array, but this is not the case if your workflow on.pull_request.branches is defined e.g. like this:

`branches: '*'`

Workaround is to define branches always in yaml list-format, but for consistency also single value should work without runtime error.

Related code in actions-utils.js:

`190: const difference = pull_request.filter((value) => !push.includes(value));`

**Comment by robertbrignull** [comment]
Thanks for bringing this up and sorry this affected you. There were some cases that we didn't account for. We've reverted the change that caused that bug on the `v1` branch so your workflow should work again, and we'll work on a fix before that change gets merged in again.

I'll close this issue as the immediate bug should be gone, but if this still affects you please do let us know.
