### ISSUE TITLE
Set a custom location for .sarif file ?

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [github/codeql-action#342]
Hi!

I was wondering, if there is an option in the analysis action, to set a custom location for the generated .sarif file, so that it could be accessible to the workflow for example as artifact or to be used by another action ?

It is currently generated inside "D:\a\repo\results\file.sarif" and unless I am doing something wrong, I can't access it from there.

**Comment by robertbrignull** [comment]
You can control where the SARIF file is placed with the `output` input to the `github/codeql-action/analyze` action.

I also tried accessing accessing the SARIF file in its default location in windows and I got an error that the file didn't exist. I'm not sure quite what's going on, whether it's file permissions issues or working directory location issues. But anyway, for now you can work around it by setting the `output` location hopefully.

**Comment by AleksIvanovSinglet** [comment]
"You can control where the SARIF file is placed with the output input to the github/codeql-action/analyze action."

I am not sure I understand, could you please give more detail i.e. may be a code snippet ?

**Comment by robertbrignull** [comment]
Yes, exactly like that. So just to fill in slightly more it would look like:
```
- uses: github/codeql-action/analyze@v1
  with: 
    output: ./codeql/
```

**Comment by AleksIvanovSinglet** [comment]
Thank you!
