### ISSUE TITLE
Action to upload created codeql database to as an artifact of the actions workflow? 

### ISSUE THREAD

**Issue by bgianfo** [github/codeql-action#355]
I'm trying to utilize CodeQL more for the open source project http://github.com/SerenityOS/serenity
Everything in the project is public, and I would like anyone to be able to download the CodeQL database to easily be able to write queries against it. Having the ability to do that from a supported action in the `codeql-action` project seems like the easiest solution, as it could upload it as part of the action artifacts mechanism already available.

Thoughts?

**Comment by robertbrignull** [comment]
Making it easy to upload a database as an artefact and making it easily available to others is definitely something that we want to do. You can rest assured that this is something that'll happen eventually, although there isn't currently any timeline on it.

**Comment by adityasharad** [comment]
Closing in favour of https://github.com/github/codeql-action/issues/263. We do have plans to do this, but it's easier to track in a single issue.
