### ISSUE TITLE
Can you use Typescript with CodeQL actions?

### ISSUE THREAD

**Issue by rsmayda** [github/codeql-action#365]
Can you use Typescript with CodeQL actions? If so can you provide a code snippet (yaml)?

**Comment by robertbrignull** [comment]
https://github.com/github/codeql-action#usage shows an example workflow file. You can also go to your repository and click "set up code scanning" and it'll generate a workflow file for you.

To analyse typescript set the `languages` input to `javascript` as CodeQL analyses both javascript and typescript together.

I hope this answers your question so I'll close this issue. If not then feel free to reopen the issue.
