### ISSUE TITLE
Source of file path originating an alert

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [github/codeql-action#383]
For each alert that is generated, there is a full path to the file the alert originates from. When I access the Code Scanning REST API, that information is not in there.

Where does it come from and is it accessible by users ?

**Comment by bogdanap** [comment]
We're extracting the information about file locations associated with the alert from the results of the CodeQL analysis. 
For the moment, this information is not included in the API responses, but we are planning on introducing it very soon.
