### ISSUE TITLE
Treat warnings as errors

### ISSUE THREAD

**Issue by 08A** [github/codeql-action#389]
related to: https://github.com/github/codeql-action/issues/304

> Currently it only marks the check run as failed for alerts that are marked as errors. The ability to treat warnings as errors is a something we're working on adding, so there's more customisation of the behaviour there.

Do you have any new information about this feature?
If you want, I can work on this. I just need some advice on the code base.

Example:
![2021-02-09-121857_545x39_scrot](https://user-images.githubusercontent.com/32521367/107356361-00db1900-6ad1-11eb-96e6-e1716eea7be1.png)
https://github.com/rizinorg/rizin/blob/dev/.github/workflows/clang-analysis.yml

This jobs should failed because the developer should be notify about new warnings.

**Comment by robertbrignull** [comment]
Apologies there hasn't been a visible progress on this feature. It is still something that's in the pipeline but unfortunately I can't say much more than that. Thank you for the offer of working on it, but unfortunately that won't really be possible as doing this would require changing private repositories and not just the codeql-action repository.

There is a workaround you could use right now to get the same effect but without it being a builtin feature. Before uploading the SARIF file in your workflow you could edit it to change the severities of the alerts. If you change the warnings to errors before uploading then code scanning will treat them as errors.

**Comment by 08A** [comment]
Thanks you for your reply.

> Apologies there hasn't been a visible progress on this feature. It is still something that's in the pipeline but unfortunately I can't say much more than that. Thank you for the offer of working on it, but unfortunately that won't really be possible as doing this would require changing private repositories and not just the codeql-action repository.

Okay, no problem

> There is a workaround you could use right now to get the same effect but without it being a builtin feature. Before uploading the SARIF file in your workflow you could edit it to change the severities of the alerts. If you change the warnings to errors before uploading then code scanning will treat them as errors.

Which tool do you recommend? I was thinking about using sed (ugly hack).
`sed -Ei 's/("ruleId": .*)/\1\n"level": "error",/' merged.sarif`

And does this workaround work with the 'classic' codeql-action?
Because I don't see any sarif file in the workflow.
Example:
https://raw.githubusercontent.com/rizinorg/rizin/dev/.github/workflows/codeql-analysis.yml

**Comment by robertbrignull** [comment]
Sed would probably work. Otherwise if you want something that will parse the structure of the JSON instead of just looking at it textually then `jq` can be used to replace values as well. You can do stuff like
```bash
jq '.foo.bar = "new value"' file.json > file2.json
```

> And does this workaround work with the 'classic' codeql-action?

The `analyze` by default uploads for you, but you can configure it to not upload and save the SARIF file to a location of your choosing. See the `output` and `upload` options at https://github.com/github/codeql-action/blob/main/analyze/action.yml. Then you can upload the resulting SARIF file using the `upload-sarif` action.

**Comment by 08A** [comment]
Thanks you, I will check.
I will close this issue.

**Comment by 08A** [comment]
I reopen this issue. But if you want I will create a new one.

I apply the recommended advice. But I don't have the expected result.
![2021-02-09-195951_227x208_scrot](https://user-images.githubusercontent.com/32521367/107413805-76ff7000-6b11-11eb-89ba-0ed95efa624d.png)

So I use https://microsoft.github.io/sarif-web-component/ to verify the artifacts file.

before:
![2021-02-09-194430_854x409_scrot](https://user-images.githubusercontent.com/32521367/107411796-3ef72d80-6b0f-11eb-9215-6f8f4cb70eea.png)

after:
![2021-02-09-194453_849x408_scrot](https://user-images.githubusercontent.com/32521367/107411825-4a4a5900-6b0f-11eb-89d4-a103ecd3cb4a.png)

As you can see, all results have an "error" level. But "Code scanning" didn't detect the new error (only detect a new warning).
![2021-02-09-200127_537x87_scrot](https://user-images.githubusercontent.com/32521367/107413931-a8783b80-6b11-11eb-9f85-56103c0f1c31.png)

[artifacts.zip](https://github.com/github/codeql-action/files/5953602/artifacts.zip)
https://github.com/rizinorg/rizin/pull/557

**Comment by robertbrignull** [comment]
Thanks for including the links to your workflow and artifacts. That was very helpful.

What you done is not wrong, but unfortunately Code Scanning currently doesn't read the severity level for each individual result. You want to instead add it to the rule object. The following should work (I think)
```
jq '.rules[] |= . + {"defaultConfiguration": {"level": "error"}}' merged.sarif > final.sarif
```
You want to add the following to each entry in the `runs[].tool.driver.rules` array
```
"defaultConfiguration" : {
  "level" : "error"
},
```

**Comment by 08A** [comment]
Your solution works.

I made a little modification:
```
jq '.runs[].tool.driver.rules[] |= . + {"defaultConfiguration": {"level": "error"}}' merged.sarif > final.sarif
```

Thanks you.
I will close this issue.
