### ISSUE TITLE
Feature Request: Separate SARIF workflow logic from CodeQL

### ISSUE THREAD

**Issue by ap0phi5** [github/codeql-action#403]
The SARIF standard supports Code Scanning output from a growing number of tools;
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning

Is there a rationale for keeping the `codeql-action/upload-sarif` action under the CodeQL hierarchy?

**Comment by alexet** [comment]
The `codeql-action/upload-sarif` can be used with any SARIF producer. It is kept in the `codeql-action` repo so we can test it and update it with all of the rest of the CodeQL action machinery. We have no plans of moving it at the moment but we will inform you of that changes.
