### ISSUE TITLE
Running codeql-analysis on all the branches of a repository

### ISSUE THREAD

**Issue by adithyaakrishna** [github/codeql-action#462]
Is it possible to run codeql-analysis on all the branches of a repo possible or not?

The action should basically run on all the branches a PR is targeted to from the Main repository. I tried searching across github but couldn’t find anything.

**Screenshot:**
![image](https://user-images.githubusercontent.com/23498248/116307042-73e85780-a7c3-11eb-96dc-433d72f69e03.png)

**Comment by aeisenberg** [comment]
Yes, you can run your analysis across all branches. There is an error in your yaml.

`**` is a special character sequence in yaml. It needs to be quoted. But even simpler would be to remove the `branches` directive entirely. If it is missing, then the workflow will be triggered on all branches.

**Comment by adithyaakrishna** [comment]
Thanks a lot @aeisenberg . If I remove the branches directive entirely, then it would look like this right?
![image](https://user-images.githubusercontent.com/23498248/116353038-bd609300-a813-11eb-829c-6b875b6d9a83.png)
Which will enable the workflow to trigger across all branches?

**Comment by aeisenberg** [comment]
This looks right to me. Have you tried it?

**Comment by adithyaakrishna** [comment]
Yes @aeisenberg 
It perfectly works 🎉

**Comment by JacquesLeRoux** [comment]
Hi,

I tried both syntaxes today but none worked.

Please see content of https://github.com/apache/ofbiz-framework/commit/91357bbf0eabd147b87385fd94cb0b139058fa12

TIA for any help

**Comment by JacquesLeRoux** [comment]
Ha wait got it, no java nor js files changed, please forget it
