### ISSUE TITLE
Prevent OOME when counting lines of code

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-action#498]
Some users, (eg- https://github.com/github/codeql/issues/5873) are seeing out of memory errors during the lines of code counting phase. A mitigation is to ensure that non-analyzed code is added to the `paths-ignore` property. However, we still should figure out why we are running out of memory in these situations.

**Comment by weswigham** [comment]
CodeQL is also pretty reliably OOMing over on the TS repo now, eg [here.](https://github.com/microsoft/TypeScript/pull/44064/checks?check_run_id=2569875009) We already [only pull in our src folder for codeQL](https://github.com/microsoft/TypeScript/blob/master/.github/codeql/codeql-configuration.yml).
