### ISSUE TITLE
Autobuild doesn't detect Meson build system

### ISSUE THREAD

**Issue by ntonnaett** [github/codeql-action#562]

**Comment by tausbn** [comment]
As far as I am aware, Meson should be supported by the autobuilder. Can you give us some more details on your setup?

**Comment by ntonnaett** [comment]
I've added it to my project at https://github.com/ntonnaett/wonder-lite. Maybe I just have to install meson in a separate step? Now I see in the logs that it actually checks on a meson.build file. But in the end the log says that it didn't detect a supported build system.

**Comment by tausbn** [comment]
Indeed, it looks to me like it failed to build with meson simply because the required binaries were not present. 

I found this example of how to install meson on GitHub Actions. Perhaps it can be of use?

https://github.com/mesonbuild/meson/blob/master/docs/markdown/Continuous-Integration.md

**Comment by ntonnaett** [comment]
Thanks for the link! I've already added all the dependencies but that collection looks useful.

Maybe the autobuilder message could be changed to something like: "A meson.build file was found, but meson was missing. Please install all dependencies first."

**Comment by tausbn** [comment]
> Maybe the autobuilder message could be changed to something like: "A meson.build file was found, but meson was missing. Please install all dependencies first."

That's a good idea. I will pass this on.

Judging by the latest Actions runs on your repo, it seems like the build is working correctly now. :tada: 

If this is indeed the case, and you have no further questions, feel free to close this issue.

**Comment by ntonnaett** [comment]
Yes, everything is working now. Thanks for your help!

**Comment by jbj** [comment]
I found the relevant snippet in [the log](https://github.com/ntonnaett/wonder-lite/runs/2821710558?check_suite_focus=true):

```
  + meson ..
  /opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/cpp/tools/do-prebuild: line 79: meson: command not found
```

I can see that's not a great message for someone who expects GitHub Actions and the autobuilder to be highly coordinated. I hope it's a great message for someone debugging their build on a platform that may or may not be the default Actions Ubuntu image.

At the moment, the autobuilder is used a lot without Actions and vice versa. When we get to a point where these products are coordinated more closely, I agree this is the sort of thing that should Just Work.
