### ISSUE TITLE
Accessing private go modules

### ISSUE THREAD

**Issue by sollie** [github/codeql-action#575]
Unsure if this belongs here or in https://github.com/github/codeql-go.

I'm struggling with running CodeQL on Go code on my onprem Enterprise Server.
We depend on internal modules hosted in a separate org. I need these modules to be pulled with SSH.

I have tried various iterations of 
```yml
env:
  GOPRIVATE: "*.ghes.server"
```
and a step with

```yml
    - name: Granting private modules access
      run: git config --global --add url."git@my.ghes.server/myorg".insteadOf "https://my.ghes.server/myorg"
```
before the CodeQL steps in my workflow without luck. I still see https-requests in the logs on my GHES instance.

I am seeing log-entries like this:
```
[2021-06-21 08:30:56] [build-err] 2021/06/21 08:30:56 Error running go tooling: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -- ./...]: exit status 1: go: my.ghes.server/myorg/myrepo@v1.0.1: reading my.ghes.server/myorg/myrepo/go.mod at revision v1.0.1: unknown revision v1.0.1
```

It this supposed to be supported? Am I misunderstanding something really basic?

**Comment by sauyon** [comment]
It should indeed be supported; to be clear, you're using both at once, right?

Does a simple `go get ...` work?

**Comment by sollie** [comment]
Ah, this is embarresing. A simple `go get` didn't work, which eventually led me to the real issue.
The action used to set up ssh-agent didn't work properly. Sorry for wasting your time.

**Comment by sauyon** [comment]
No problem, glad to know this is resolved.
