### ISSUE TITLE
CodeQL Action not in the Marketplace?

### ISSUE THREAD

**Issue by johnthagen** [github/codeql-action#596]
I was surprised when I searched for this action it wasn't in the marketplace:

https://github.com/marketplace?type=actions&query=codeql-action+

<img width="610" alt="Screenshot 2021-06-25 094326" src="https://user-images.githubusercontent.com/10340167/123433773-cebae700-d599-11eb-9db5-dbfe5b330013.png">

Are the GitHub authored Actions special cased and included by default? I think it could make some of these Actions more discoverable if they were searchable in the marketplace.

Or did I use the incorrect search term?

**Comment by criemen** [comment]
Hi,
that's curious! I'll investigate this with the team, and report back. Surely there are _some_ actions from us in the marketplace: https://github.com/marketplace?type=&verification=&query=publisher%3Agithub+

**Comment by criemen** [comment]
Okay, I got a quick response: The `codeql-action` technically consists of 4 actions, and these can't be bundled on the marketplace.
We see little value in offering 4 different actions "CodeQL: Init", "CodeQL: Analyze" etc, as they only make sense when used together.

Thus, as long as the marketplace doesn't support releasing groups of actions, `codeql-action` will not be in the marketplace.
