### ISSUE TITLE
Autobuild fails with gradle and openjdk17

### ISSUE THREAD

**Issue by ari** [github/codeql-action#756]
https://github.com/ishgroup/oncourse/runs/3744777334?check_suite_focus=true

So that I can avoid using autobuild, what gradle task does it need to execute? Does it just need to compile Java code? Distributions?

**Comment by bmuskalla** [comment]
@ari see also https://github.com/gradle/gradle/issues/16857

**Comment by ari** [comment]
Perhaps there are some gradle issues for some people, but my project builds just find with gradle (see all the other github actions in that same repo). It is only autobuild that fails. Which I could just remove, but with autobuild as closed source it is not clear what exactly it does.

Can I just use the gradle "assemble" target?

**Comment by MathiasVP** [comment]
> Perhaps there are some gradle issues for some people, but my project builds just find with gradle (see all the other github actions in that same repo). It is only autobuild that fails.

That's not actually true. Take a look at the most [recent api-tests (17)](https://github.com/ishgroup/oncourse/runs/3758509002?check_suite_focus=true#step:10:27) job. That one fails with the same error message.

**Comment by ari** [comment]
Oops. You are right. I need to see why github thinks that test passed when in fact it completely failed.

**Comment by MathiasVP** [comment]
Thanks for confirming. Since this is not `codeql-action` specific I'll close this issue. Feel free to open a new issue if you hit another problem.
