### ISSUE TITLE
Scan against a .NET 5.0 Web Application encounters an unhandled literal type error

### ISSUE THREAD

**Issue by BeigeBadger** [github/codeql-action#772]
```
Interpreting results for csharp
Analysis produced the following diagnostic data:

| Severity |                          Message                           |
+----------+------------------------------------------------------------+
| error    | Unexpected C# extractor error: Unhandled literal type      |
| none     | (31 results for diagnostic "Successfully extracted files") |
Analysis produced the following metric data:

|               Metric                | Value |
+-------------------------------------+-------+
| Total lines of code in the database |  1345 |

/opt/hostedtoolcache/CodeQL/0.0.0-20210921/x64/codeql/codeql database print-baseline /home/runner/work/_temp/codeql_databases/csharp
```

The repo is public and can be accessed [here](https://github.com/BeigeBadger/animal-adoption-portal-devsecops).

The run in question is available [here](https://github.com/BeigeBadger/animal-adoption-portal-devsecops/runs/3879231288?check_suite_focus=true).

My workflow file was generated automatically by following the Setting up code scanning using actions section in the official documentation [here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-using-actions].

I encounter this issue whether I use automatic build or not, here is a [workflow run](https://github.com/BeigeBadger/animal-adoption-portal-devsecops/runs/3879231358?check_suite_focus=true) and the [workflow file](https://github.com/BeigeBadger/animal-adoption-portal-devsecops/actions/runs/1336279241/workflow) for a workflow that uses a manual step and gets the same error.

Let me know if you need any further information.

**Comment by adityasharad** [comment]
Thanks for the detailed information! I believe you can safely ignore the `Unhandled literal type` error -- it is not critical enough to prevent the CodeQL database from being created and analysed.

However we would be interested in seeing which source code elements led to the error. Would you be able to modify your workflow to upload the SARIF results file, and share that with us? The change will look something like this:
```yaml
- name: CodeQL analysis
  uses: github/codeql-action@v1/analyze
  with:
    output: results
- name: Upload
  uses: actions/upload-artifact@v2
  with:
    name: sarif
    path: results
```
