### ISSUE TITLE
Post Results to PR

### ISSUE THREAD

**Issue by manpreet-agoro** [github/codeql-action#803]
Is there an option to post the security results to a calling PR instead of the security hub itself? I had like to have every PR list all the security scan failures, even if they are ignored they should be there just to make sure its not "I didnt' check  the security tab"

**Comment by adityasharad** [comment]
Hello. Information about code scanning alerts on PRs can be found in several locations:
- the Security tab, when filtered to the PR or branch
- as annotations on the affected code in the `Files changed` tab of the PR
- in the `Code scanning results` check on the PR, visible in the `Checks` tab of the PR as well as the check summary view at the bottom of the `Conversations` tab

Where possible, these views will describe the alerts that were newly introduced by the PR, not every existing alert. 

I hope these are sufficient to show you the information you're looking for -- please let us know if you have further questions. See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests for more information.
