### ISSUE TITLE
CodeQL support for VS 2022 with C++.

### ISSUE THREAD

**Issue by pjmlp** [github/codeql-action#821]
Now that I migrated one of my projects into 2022 I cannot use CodeQL  any longer, given it only supports VS 2019.

Is there any roadmap available regarding future support for VS 2022 toolchain?

**Comment by hvitved** [comment]
Have you tried running the analysis with VS2022? It might just work.

**Comment by pjmlp** [comment]
GitHub workflow fails as it cannot recognise the tooling on repo changes.

Naturally it works on VS 2022 itself.

**Comment by hvitved** [comment]
Can you post (a link to) the failure? VS 2022 should be available in actions workflows as of yesterday: https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/.

**Comment by pjmlp** [comment]
Sure, https://github.com/pjmlp/AStarDemo/actions/runs/1459118154/attempts/1

I will check the blog later today.

**Comment by pjmlp** [comment]
I have updated the run environment to windows-2022, yet the C++/WinRT toolchain seems to behave in a different way and autobuild isn't able to find the source code, not sure what else I am supposed to change on, directly calling msbuild also did not help.

https://github.com/pjmlp/AStarDemo/runs/4255785760

**Comment by hvitved** [comment]
Hi

At least now the code is able to build (the "Autobuild" step succeeds). @github/codeql-c can you take a look at the `No source code was seen and extracted` issue?

**Comment by pjmlp** [comment]
I fail to see why this is an issue with VS 2022, when everything was working out of the box with VS 2019.

Additionally, the documentation on how to fix the issue is unclear how I am supposed to call MSBuild for C++ UWP code, in a way that makes CodeQL happy.

This is a toy project, so I am not losing any more time with it, feel free to close the ticket.

**Comment by hvitved** [comment]
> I fail to see why this is an issue with VS 2022, when everything was working out of the box with VS 2019.

VS 2022 is not [officially supported](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/), I was just hoping that it might work, but it appears to not be the case.

**Comment by pjmlp** [comment]
Thanks for the support.

**Comment by sashabu** [comment]
@pjmlp, we fixed some issues around build tracing on Windows Server 2022 and Windows 11 in CodeQL CLI 2.8.3 (which is now rolled out on Actions). While we still don't have official support for VS 2022, would you might giving it another try in case it happens to work now?

**Comment by pjmlp** [comment]
Thanks for pinging me back, but it doesn't seem like it is worth the effort, given:

> C++20 support is currently in beta. Supported for GCC on Linux only. Modules are not supported.

I am using C++20 and modules.
