### ISSUE TITLE
CodeQL name and custom tags

### ISSUE THREAD

**Issue by iHarshalAgarwal** [github/codeql-action#836]
Hi, I have a single repository with multiple projects, and I am trying to use a single codeql yml file for all my projects in that repository.

Is there a way to set the "name" value dynamically (maybe using workflow_dispatch or something else)?

I was also looking for an approach to add some custom tags/keywords to my scans, which should allow me to filter the scan results.

for instance, I have a feature branch, that affects multiple projects but refers to the same codeql yml file.
When the workflows are triggered for each project, the workflow name is the same for all these scans. I know we can use the inbuilt filters, but it would be great if we can somehow set such stuff dynamically.

**Comment by aeisenberg** [comment]
> I was also looking for an approach to add some custom tags/keywords to my scans, which should allow me to filter the scan results.

For this part, I think something like [categories ](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-a-category-for-the-analysis)would help you. Categories allow you to run multiple scans on the same repository and commit. It's useful for monorepos, like yours. 

As for the first part of your question regarding the _name_, I'm not exactly sure what you are asking. Where are you looking at the name of the workflow? Is this in the _Actions_ tab of your repository? How do you trigger the workflow for the different parts of the project?

**Comment by iHarshalAgarwal** [comment]
Thank you, @aeisenberg for quick response.

I tried to assign some text to categories but I could not see the filter in code security alerts page.

I am referring to the Actions tab (name:"CodeQL" in the yml file).

I am using workflow_dispatch and the scans are triggered from a Jenkins job.

**Comment by adityasharad** [comment]
The name in the Actions tab and the first segment of the Actions checks is taken from the `name` field of the Actions workflow -- you can change that from `CodeQL` to any string of your choosing. The name of the final check `Code scanning results / CodeQL` cannot be changed.

**Comment by iHarshalAgarwal** [comment]
Yes, I was looking for a way to set the name field dynamically. it will be easy for me to see which project does the scan belongs to in my mono repository.

For instance, i wanted to append the project name (CodeQL) to the name (CodeQL-ProjectName passed as input) field in codeql yml when the scan is triggered.

**Comment by iHarshalAgarwal** [comment]
> The name in the Actions tab and the first segment of the Actions checks is taken from the `name` field of the Actions workflow -- you can change that from `CodeQL` to any string of your choosing. The name of the final check `Code scanning results / CodeQL` cannot be changed.

Is there a way to change the 'name' field based on the workflow_dispatch input value?

**Comment by aeisenberg** [comment]
No, the workflow name is fixed. You _could_ try creating multiple workflows with unique names and then they could all call the same composite action, which appropriately does the code scanning. You would need to create your own composite action, though.

**Comment by iHarshalAgarwal** [comment]
> No, the workflow name is fixed. You _could_ try creating multiple workflows with unique names and then they could all call the same composite action, which appropriately does the code scanning. You would need to create your own composite action, though.

That makes sense. Do you have any example I could refer?

**Comment by adityasharad** [comment]
I would recommend using a matrix workflow: see https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed and https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-a-category-for-the-analysis for examples. The examples focus on matrixing over different languages, but you can adapt it so that each matrixed job builds a different part of your monorepo, and set the category accordingly. The matrix job name (including the matrix parameters) will appear as the second part of the check name (after the `/`); as we discussed earlier you cannot change the first part dynamically.
