### ISSUE TITLE
Support VS 2022

### ISSUE THREAD

**Issue by blu3mania** [github/codeql-action#850]
I updated one of my repositories to use VS 2022 and MSVC Tools v143 to build, and although I could use the latest "windows-2022" hosted runner to successfully build my solution, CodeQL failed. After digging around I found #821 which is the exact same issue, and from [the linked support page](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/) it states that VS support is only up to 2019.

Can VS 2022 support be added? Thanks.

**Comment by blu3mania** [comment]
For now I reverted my repository back to use VS 2019.

**Comment by hmakholm** [comment]
Yes, database creation on Windows 2022 is currently broken. The system libraries in the OS update change some details that CodeQL was depending upon for observing what the build process does. We have some engineers working urgently on getting it to work again, but it's complicated and we have no firm ETA for a fix yet. :-(

**Comment by hmakholm** [comment]
This eventually got fixed.
