### ISSUE TITLE
Add speed up methods for the action

### ISSUE THREAD

**Issue by darklight9811** [github/codeql-action#864]
# Summary
codeql-action is amazing to find vulnerabilities, but it's speed can end up being a bottleneck. Maybe add caching to it would help, for files changed (hashed) so it could only analyze code that was actually updated.

**Comment by aeisenberg** [comment]
Thank you for your suggestion. Unfortunately, this is not viable. Many of our analyses are global. Therefore a change in _any_ file could trigger warnings in any other file. 

It is theoretically possible that if queries are labelled as local, we could avoid running them on files that have not changed. This would be a big change to our system and it is not currently on our roadmap.

**Comment by darklight9811** [comment]
@aeisenberg oh, thank you for your attention. Sadly this is a huge bottleneck in my workflow. And the fact that it doesn't stop the steps when it find something wrong actually seems problematic. But thx

**Comment by jentfoo** [comment]
For anyone in the future, it does look like an incremental CodeQL solution is being explored: https://githubnext.com/projects/incremental-codeql/
