### ISSUE TITLE
upload-serif@v1: Unable to override commit_sha

### ISSUE THREAD

**Issue by benmoss** [github/codeql-action#890]
I am trying to have a periodic action that checks for vulnerabilities in the latest release of my repo. The [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) event sets `GITHUB_SHA` and `GITHUB_REF` to the latest commit of the default branch, which is not what I want.

I've tried [setting these env vars on the step](https://gist.github.com/benmoss/7753df08c30c41ecb3ad36be75dae981#file-trivy-release-scan-yml-L37-L43) but it seems to have no effect, it still ends up uploading as the latest commit on my default branch. Maybe GitHub doesn't allow these to be overridden. I tried doing a checkout of that tag in a prior step as well and it also had no effect.

If these action just had a `commit_sha`/`ref` input that'd be a simple enough workaround.

**Comment by aeisenberg** [comment]
Possibly related to #889.

**Comment by benmoss** [comment]
> Possibly related to #889.

Nice, I think that exactly fixes my issue if I'm reading it correctly
