### ISSUE TITLE
Scan multiple docker images & upload sarif report

### ISSUE THREAD

**Issue by chaiyd** [github/codeql-action#895]
- Scan multiple docker images in the same workflow and upload multiple sarif reports。
   How do I need to set the path ？
   At the moment it looks like he only uploaded the scan results of the last docker images.
- workflows
   - https://github.com/chaiyd/docker/blob/master/.github/workflows/rocketmq.yml

**Comment by aeisenberg** [comment]
I think you will want to use the `category` option in the upload sarif action. See [here for more information](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions). 

You must ensure that each of your distinct analyses uses a different category in order to ensure they do not overwrite each other.

**Comment by chaiyd** [comment]
> I think you will want to use the `category` option in the upload sarif action. See [here for more information](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions).
> 
> You must ensure that each of your distinct analyses uses a different category in order to ensure they do not overwrite each other.

Thx, this is very useful.

Do you have any good suggestions for images that are too large? while scanning
`No space left on device`


```
Run anchore/scan-action@v3
/usr/bin/chmod +x /home/runner/work/_temp/7f1630ec-fd15-4634-9572-51d6012b71cb
/home/runner/work/_temp/7f1630ec-fd15-4634-9572-51d6012b71cb -b /home/runner/work/_temp/7f1630ec-fd15-4634-9572-51d6012b71cb_grype v0.27.3
anchore/grype info checking GitHub for tag 'v0.27.3'
anchore/grype info found version: 0.27.3 for v0.27.3/linux/amd64
anchore/grype info installed /home/runner/work/_temp/7f1630ec-fd15-4634-9572-51d6012b71cb_grype/grype

Analyzing: ***/conda:cuda11.6.0-devel-3.7.5-ubuntu18.04
Executing: grype -o json --fail-on medium ***/conda:cuda11.6.0-devel-3.7.5-ubuntu18.04
grype output...
  1 error occurred:
  	* failed to catalog: could not fetch image '***/conda:cuda11.6.0-devel-3.7.5-ubuntu18.04': unable to save image tar: Error response from daemon: mkdir /var/lib/docker/overlay2/8c3c666e3a079aa517134dad42187e4689dc68f456f9b407e75837098c4c644c/merged: no space left on device
  
  
Error: Unable to parse grype output: SyntaxError: Unexpected end of JSON input
Error: TypeError: Cannot read property 'matches' of undefined
```

**Comment by aibaars** [comment]
> Do you have any good suggestions for images that are too large? while scanning
> `No space left on device`

If you are scanning multiple images in a single job then you could try clearing up the space taken up by the previously analyzed images. See: https://stackoverflow.com/questions/37518096/cleanup-disk-space-occupied-by-docker-images . 

Alternatively, you can use a ["build matrix"](https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs) to have each image be analyzed in a separate job.

If that still doesn't work then you could switch to a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) with more diskspace.The default Actions runners have only 14GB disk space.

**Comment by chaiyd** [comment]
> > Do you have any good suggestions for images that are too large? while scanning
> > `No space left on device`
> 
> If you are scanning multiple images in a single job then you could try clearing up the space taken up by the previously analyzed images. See: https://stackoverflow.com/questions/37518096/cleanup-disk-space-occupied-by-docker-images .
> 
> Alternatively, you can use a ["build matrix"](https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs) to have each image be analyzed in a separate job.
> 
> If that still doesn't work then you could switch to a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) with more diskspace.The default Actions runners have only 14GB disk space.

OK，thanks.
I used `docker image prune -a -f`, but the images itself is too big. I try [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) .
