### ISSUE TITLE
C++ suppression doesn't work

### ISSUE THREAD

**Issue by nirbar** [github/codeql-action#926]
I'm trying to suppress a warning in C++ code, however the suppression doesn't work for me.

Code:
~~~
	szXmlPath = (LPCWSTR)details.xml_path().c_str(); // lgtm[cpp/incorrect-string-type-conversion]
~~~

CodeQL scan result:
![image](https://user-images.githubusercontent.com/4049068/154072797-392d4255-e2de-4e2a-8999-7d7adfc4585f.png)

The code is on master branch, so this isn't a pull request issue.
Any help would be appreciated

**Comment by edoardopirovano** [comment]
Greetings, thanks for reaching out to us! The alert suppression comments you have used there apply to LGTM.com and do not suppress alerts on GitHub's Code Scanning. Currently, it is not possible to suppress alerts on Code Scanning with a comment but you can dismiss them from the web interface under the _Dismiss_ dropdown at the top right of the alert page. See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/managing-code-scanning-alerts-for-your-repository#dismissing-or-deleting-alerts for more information about dismissing and/or deleting alerts in Code Scanning.

I hope that's helpful, do let me know if I can be of any further help!
