### ISSUE TITLE
`wait-for-processing` fails on pull requests from forks

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-action#963]
The addition of the flag to `wait-for-processing` to complete causes pull requests from forks to fail. We are working on a fix for this internally. This is the public-facing version of the issue and we will close this issue when the internal issue is closed.

**Comment by andreaTP** [comment]
Any update on this open issue @aeisenberg ?

cc. @abstractj

**Comment by aeisenberg** [comment]
There is still some work to do.

**Comment by andreaTP** [comment]
Hi @aeisenberg , is there any update on this issue?

We are approximating the results limit:
https://github.com/keycloak/keycloak/runs/6075094447?check_suite_focus=true#step:7:5635

Given the unexpected delay in the server-side implementation of it, would you reconsider merging a PR on the lines of #960 ? The implementation is super straight forward and it won't introduce technical debt.

cc. @abstractj

**Comment by aeisenberg** [comment]
Apologies for the wait. All of the work is complete. I am just verifying that the changes are all rolled out. 

In the meantime, you can try adding back `wait-for-processing` in your `codeql-action/analyze` step. I am not sure if it is ready yet. All the bits have been fixed, but just not sure if they are deployed yet.

**Comment by andreaTP** [comment]
Thanks, @aeisenberg for the feedback!

**Comment by aeisenberg** [comment]
This has been fixed for a while now. Forgot to close this issue.
