### ISSUE TITLE
Failed when using CodeQL on a .Net/C# Application

### ISSUE THREAD

**Issue by BrightRan** [github/codeql-action#98]
Associated community ticket: https://github.community/t/using-codeql-on-a-net-c-application/121055

The customer enabled **CodeQL** on an older project that uses .Net framework. the repository is [here](https://github.com/glav/Glav.CacheAdapter).

He referenced to the example shared in the **README** of the **CodeQL Action** (see [here](https://github.com/github/codeql-action#usage)) to setup his workflow, but the "**Autobuild**" step failed.
Then he tried to run the build manually as suggested in the **README**, but the "**Perform CodeQL Analysis**" step failed after the build.
The workflow that ran failed is [here](https://github.com/glav/Glav.CacheAdapter/runs/824975191?check_suite_focus=true).

**Comment by robertbrignull** [comment]
This is unfortunately a known issue with tracing some versions of .Net on linux. We have a little information about it at https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-code-scanning but the basic advice is to add `p:UseSharedCompilation=false` to your build command. Note although that page says `dotnet build`, the same advice applies to `msbuild`. I'd appreciate if you could try that and we'll see if it works.

**Comment by glav** [comment]
Thanks for the response and I can confirm that adding the /p:UseSharedCompilation=false flag to msbuild resolved the issue.

**Comment by robertbrignull** [comment]
Ok, glad it worked for you. I'll close this issue as solved.
