### ISSUE TITLE
codeql-action-autobuild can build javafx app

### ISSUE THREAD

**Issue by SummerSec** [github/codeql-action#985]
codeql-action-autobuild can build javafx app

for example https://github.com/SummerSec/SPATool/runs/5570534437?check_suite_focus=true

**Comment by aibaars** [comment]
You are missing the javafx classes on the classpath. I believe Oracle JDK used to contain javafx by default. However, GitHub Actions runners have OpenJDK installed. 

I think you can fix the problem by adding the following to your `pom.xml` file:
```
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>17</version>
</dependency>
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-graphics</artifactId>
    <version>17</version>
</dependency>
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-fxml</artifactId>
    <version>17</version>
</dependency>
```

**Comment by smowton** [comment]
Alternatively I note that in your successful build https://github.com/SummerSec/SPATool/runs/5404203906?check_suite_focus=true you intentionally install

```
Run actions/setup-java@v1
  with:
    distribution: Liberica
    java-version: 1.8
    java-package: jdk+fx
```

I suspect if you added that same install directive to your codeql.yml you would get a successful build.

**Comment by SummerSec** [comment]
> 或者，我注意到，在成功的构建 https://github.com/SummerSec/SPATool/runs/5404203906?check_suite_focus=true 您有意安装
> 
> ```
> Run actions/setup-java@v1
>   with:
>     distribution: Liberica
>     java-version: 1.8
>     java-package: jdk+fx
> ```
> 
> 我怀疑如果你在你的 codeql.yml 中添加了相同的安装指令，你会得到一个成功的构建。


I'm going to make it this way, I don't modify much where, but I guess if adding this in the `automatic build` would not be a better point than having the user and this config?

**Comment by smowton** [comment]
Suggest adding the step starting at https://github.com/SummerSec/SPATool/blob/main/.github/workflows/maven.yml#L19

Add it at https://github.com/SummerSec/SPATool/blob/main/.github/workflows/codeql.yml#L42

The CodeQL yml file is a normal Actions script, and can do all sorts of normal setup steps before the `github/codeql-action/init@v1` step.

**Comment by smowton** [comment]
https://github.com/SummerSec/SPATool/pull/4

**Comment by SummerSec** [comment]
> 

thank you very much agent ！

**Comment by SummerSec** [comment]
I noticed that there is such a command in the process of codeql-action, but I did not find the `java-queries-builtin.qls` file in the command. Where can I get this file?

![image](https://user-images.githubusercontent.com/47944478/159214926-62032217-dd6d-4c37-8ada-3c874fb7ff12.png)

**Comment by aibaars** [comment]
@SummerSec That file is generated here https://github.com/github/codeql-action/blob/b1c781d3983c105067e87232b504af53d61f803b/src/analyze.ts#L371-L372

**Comment by SummerSec** [comment]
> @SummerSec That file is generated here
> 
> https://github.com/github/codeql-action/blob/b1c781d3983c105067e87232b504af53d61f803b/src/analyze.ts#L371-L372

thanks!
